#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

fn main() {
    // .varg:1
    let mut g = varg_runtime::graph::__varg_graph_open(&"team_graph".to_string());
    // .varg:2
    let mut alice = varg_runtime::graph::__varg_graph_add_node(
        &g,
        &"Person".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Alice".to_string()),
            ("role".to_string(), "Engineer".to_string()),
        ]),
    );
    // .varg:3
    let mut bob = varg_runtime::graph::__varg_graph_add_node(
        &g,
        &"Person".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Bob".to_string()),
            ("role".to_string(), "Designer".to_string()),
        ]),
    );
    // .varg:4
    let mut charlie = varg_runtime::graph::__varg_graph_add_node(
        &g,
        &"Person".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Charlie".to_string()),
            ("role".to_string(), "PM".to_string()),
        ]),
    );
    // .varg:5
    let mut varg = varg_runtime::graph::__varg_graph_add_node(
        &g,
        &"Project".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Varg".to_string()),
            ("status".to_string(), "active".to_string()),
        ]),
    );
    // .varg:6
    varg_runtime::graph::__varg_graph_add_edge(
        &g,
        alice,
        &"works_on".to_string(),
        varg,
        &std::collections::HashMap::from([]),
    );
    // .varg:7
    varg_runtime::graph::__varg_graph_add_edge(
        &g,
        bob,
        &"works_on".to_string(),
        varg,
        &std::collections::HashMap::from([]),
    );
    // .varg:8
    varg_runtime::graph::__varg_graph_add_edge(
        &g,
        alice,
        &"knows".to_string(),
        bob,
        &std::collections::HashMap::from([]),
    );
    // .varg:9
    varg_runtime::graph::__varg_graph_add_edge(
        &g,
        bob,
        &"knows".to_string(),
        charlie,
        &std::collections::HashMap::from([]),
    );
    // .varg:10
    let mut people = varg_runtime::graph::__varg_graph_query(&g, &"Person".to_string());
    // .varg:11
    println!("{}", format!("People: {}", self.len() as i64));
    // .varg:12
    let mut projects = varg_runtime::graph::__varg_graph_query(&g, &"Project".to_string());
    // .varg:13
    println!("{}", format!("Projects: {}", self.len() as i64));
    // .varg:14
    let mut one_hop =
        varg_runtime::graph::__varg_graph_traverse(&g, alice, 1, &"knows".to_string());
    // .varg:15
    println!("{}", format!("Alice knows (1 hop): {}", self.len() as i64));
    // .varg:16
    let mut two_hop =
        varg_runtime::graph::__varg_graph_traverse(&g, alice, 2, &"knows".to_string());
    // .varg:17
    println!("{}", format!("Alice knows (2 hops): {}", self.len() as i64));
    // .varg:18
    let mut bob_neighbors = varg_runtime::graph::__varg_graph_neighbors(&g, bob);
    // .varg:19
    println!("{}", format!("Bob neighbors: {}", self.len() as i64));
    // .varg:20
    println!("{}", "Knowledge graph demo complete!".to_string());
}
