// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

struct TestInterp {
    pub name: String,
    pub age: i64,
}

impl TestInterp {
    pub fn new() -> Self {
        let mut __self = TestInterp {
            name: String::new(),
            age: 0,
        };
        __self.Init();
        __self
    }
    pub fn Init(&mut self) {
        self.name = "World".to_string();
        self.age = 42;
    }
    pub fn Run(&mut self) {
        let mut msg = format!("Hello {}, you are {} years old!", self.name, self.age);
        println!("{:?}", msg);
        let mut calc = format!("Result: {}", self.age + 10);
        println!("{:?}", calc);
    }
}

