// Include the autogenerated Rust code from our Varg Compiler (vargc)
include!("../../../main.rs");

fn main() {
    println!("--- Varg OS EXPERIMENTAL RUNTIME RING 3 ---");
    println!("Bootstrapping System Agent: VectorStore");

    // The struct `VectorStore` was generated by `vargc` from `main.varg`
    let mut store = VectorStore {};

    // Call the compiled .varg method
    store.init();

    println!("--- EXECUTION COMPLETE ---");
}
