// Include the autogenerated Rust code from our Varg Compiler (vargc)
include!("../../../main.rs");

fn main() {
    println!("--- varg OS EXPERIMENTAL RUNTIME RING 3 ---");
    println!("Bootstrapping System Agent: VectorStore");
    
    // The struct `VectorStore` was generated by `vargc` from `main.varg`!
    let mut store = VectorStore {};
    
    // Call the `.varg` method `Init` which we compiled
    store.Init();
    
    println!("--- EXECUTION COMPLETE ---");
}
