#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

fn main() {
    // .varg:1
    let mut mem = varg_runtime::memory::__varg_memory_open(&"assistant".to_string());
    // .varg:2
    varg_runtime::memory::__varg_memory_set(
        &mem,
        &"current_task".to_string(),
        &"research Varg compiler".to_string(),
    );
    // .varg:3
    varg_runtime::memory::__varg_memory_set(&mem, &"user_name".to_string(), &"Alice".to_string());
    // .varg:4
    let mut task = varg_runtime::memory::__varg_memory_get(
        &mem,
        &"current_task".to_string(),
        &"none".to_string(),
    );
    // .varg:5
    println!("{}", format!("Current task: {}", task));
    // .varg:6
    varg_runtime::memory::__varg_memory_store(
        &mem,
        &"User asked about Rust performance benchmarks".to_string(),
        &std::collections::HashMap::from([("topic".to_string(), "performance".to_string())]),
    );
    // .varg:7
    varg_runtime::memory::__varg_memory_store(
        &mem,
        &"Discussed compiler optimization strategies".to_string(),
        &std::collections::HashMap::from([("topic".to_string(), "compiler".to_string())]),
    );
    // .varg:8
    varg_runtime::memory::__varg_memory_store(
        &mem,
        &"User wants to learn about async programming".to_string(),
        &std::collections::HashMap::from([("topic".to_string(), "async".to_string())]),
    );
    // .varg:9
    let mut episodes = varg_runtime::memory::__varg_memory_episode_count(&mem);
    // .varg:10
    println!("{}", format!("Episodes stored: {}", episodes));
    // .varg:11
    let mut relevant =
        varg_runtime::memory::__varg_memory_recall(&mem, &"compiler performance".to_string(), 2);
    // .varg:12
    println!(
        "{}",
        format!("Relevant memories: {}", relevant.len() as i64)
    );
    // .varg:13
    varg_runtime::memory::__varg_memory_add_fact(
        &mem,
        &"Language".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Varg".to_string()),
            ("type".to_string(), "compiled".to_string()),
        ]),
    );
    // .varg:14
    varg_runtime::memory::__varg_memory_add_fact(
        &mem,
        &"Language".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Rust".to_string()),
            ("type".to_string(), "compiled".to_string()),
        ]),
    );
    // .varg:15
    let mut languages =
        varg_runtime::memory::__varg_memory_query_facts(&mem, &"Language".to_string());
    // .varg:16
    println!("{}", format!("Known languages: {}", languages.len() as i64));
    // .varg:17
    varg_runtime::memory::__varg_memory_clear_working(&mem);
    // .varg:18
    let mut cleared = varg_runtime::memory::__varg_memory_get(
        &mem,
        &"current_task".to_string(),
        &"cleared".to_string(),
    );
    // .varg:19
    println!("{}", format!("After clear: {}", cleared));
    // .varg:20
    println!("{}", "Agent memory demo complete!".to_string());
}
