#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

trait __VargFmt {
    fn __varg_fmt(&self) -> String;
}
macro_rules! __varg_fmt_display { ($($t:ty),*) => { $(impl __VargFmt for $t { fn __varg_fmt(&self) -> String { self.to_string() } })* } }
__varg_fmt_display!(
    String, bool, i8, i16, i32, i64, i128, u8, u16, u32, u64, u128, usize, isize, f32, f64
);
impl __VargFmt for &str {
    fn __varg_fmt(&self) -> String {
        self.to_string()
    }
}
impl<T: std::fmt::Debug> __VargFmt for Vec<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<K: std::fmt::Debug, V: std::fmt::Debug> __VargFmt for std::collections::HashMap<K, V> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<T: std::fmt::Debug> __VargFmt for std::collections::HashSet<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug> __VargFmt for (A, B) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug, C: std::fmt::Debug> __VargFmt for (A, B, C) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}

fn main() {
    // .varg:1
    let mut mem = varg_runtime::memory::__varg_memory_open(&"assistant".to_string());
    // .varg:2
    varg_runtime::memory::__varg_memory_set(
        &mem,
        &"current_task".to_string(),
        &"research Varg compiler".to_string(),
    );
    // .varg:3
    varg_runtime::memory::__varg_memory_set(&mem, &"user_name".to_string(), &"Alice".to_string());
    // .varg:4
    let mut task = varg_runtime::memory::__varg_memory_get(
        &mem,
        &"current_task".to_string(),
        &"none".to_string(),
    );
    // .varg:5
    println!("{}", format!("Current task: {}", (task).__varg_fmt()));
    // .varg:6
    varg_runtime::memory::__varg_memory_store(
        &mem,
        &"User asked about Rust performance benchmarks".to_string(),
        &std::collections::HashMap::from([("topic".to_string(), "performance".to_string())]),
    );
    // .varg:7
    varg_runtime::memory::__varg_memory_store(
        &mem,
        &"Discussed compiler optimization strategies".to_string(),
        &std::collections::HashMap::from([("topic".to_string(), "compiler".to_string())]),
    );
    // .varg:8
    varg_runtime::memory::__varg_memory_store(
        &mem,
        &"User wants to learn about async programming".to_string(),
        &std::collections::HashMap::from([("topic".to_string(), "async".to_string())]),
    );
    // .varg:9
    let mut episodes = varg_runtime::memory::__varg_memory_episode_count(&mem);
    // .varg:10
    println!(
        "{}",
        format!("Episodes stored: {}", (episodes).__varg_fmt())
    );
    // .varg:11
    let mut relevant =
        varg_runtime::memory::__varg_memory_recall(&mem, &"compiler performance".to_string(), 2);
    // .varg:12
    println!(
        "{}",
        format!(
            "Relevant memories: {}",
            (relevant.len() as i64).__varg_fmt()
        )
    );
    // .varg:13
    varg_runtime::memory::__varg_memory_add_fact(
        &mem,
        &"Language".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Varg".to_string()),
            ("type".to_string(), "compiled".to_string()),
        ]),
    );
    // .varg:14
    varg_runtime::memory::__varg_memory_add_fact(
        &mem,
        &"Language".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Rust".to_string()),
            ("type".to_string(), "compiled".to_string()),
        ]),
    );
    // .varg:15
    let mut languages =
        varg_runtime::memory::__varg_memory_query_facts(&mem, &"Language".to_string());
    // .varg:16
    println!(
        "{}",
        format!("Known languages: {}", (languages.len() as i64).__varg_fmt())
    );
    // .varg:17
    varg_runtime::memory::__varg_memory_clear_working(&mem);
    // .varg:18
    let mut cleared = varg_runtime::memory::__varg_memory_get(
        &mem,
        &"current_task".to_string(),
        &"cleared".to_string(),
    );
    // .varg:19
    println!("{}", format!("After clear: {}", (cleared).__varg_fmt()));
    // .varg:20
    println!("{}", "Agent memory demo complete!".to_string());
}
