#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

struct ClawLite {}

impl ClawLite {
    pub fn PrintUsage(&mut self) {
        // .varg:1
        let mut bold = "\x1b[1m".to_string();
        // .varg:2
        let mut cyan = (match "cyan".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:3
        let mut reset = "\x1b[0m".to_string();
        // .varg:4
        println!(
            "{}",
            format!(
                "{}claw_lite{} — tiny CLI agent harness in Varg",
                bold, reset
            )
        );
        // .varg:5
        println!("{}", "".to_string());
        // .varg:6
        println!("{}", format!("{}USAGE{}", cyan, reset));
        // .varg:7
        println!("{}", "  claw_lite <subcommand> [args...]".to_string());
        // .varg:8
        println!("{}", "".to_string());
        // .varg:9
        println!("{}", format!("{}SUBCOMMANDS{}", cyan, reset));
        // .varg:10
        println!(
            "{}",
            "  doctor          Check environment health".to_string()
        );
        // .varg:11
        println!(
            "{}",
            "  exec <cmd>      Spawn a subprocess and stream its stdout".to_string()
        );
        // .varg:12
        println!(
            "{}",
            "  colors          Show all ANSI color codes".to_string()
        );
        // .varg:13
        println!(
            "{}",
            "  inspect <path>  Inspect a filesystem path".to_string()
        );
    }
    pub fn Doctor(&mut self) {
        // .varg:14
        let mut bold = "\x1b[1m".to_string();
        // .varg:15
        let mut green = (match "green".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:16
        let mut red = (match "red".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:17
        let mut yellow = (match "yellow".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:18
        let mut reset = "\x1b[0m".to_string();
        // .varg:19
        println!("{}", format!("{}claw_lite doctor{}", bold, reset));
        // .varg:20
        println!("{}", "".to_string());
        // .varg:21
        let mut home = std::env::var("HOME".to_string()).unwrap_or_default();
        // .varg:22
        if home == "".to_string() {
            // .varg:23
            home = std::env::var("USERPROFILE".to_string()).unwrap_or_default();
        }
        // .varg:24
        if home == "".to_string() {
            // .varg:25
            println!(
                "{}",
                format!(
                    "  {}FAIL{}  no HOME or USERPROFILE in environment",
                    red, reset
                )
            );
        } else {
            // .varg:26
            println!(
                "{}",
                format!("  {}OK{}    home directory: {}", green, reset, home)
            );
        }
        // .varg:27
        if home != "".to_string() {
            // .varg:28
            if std::path::Path::new(&home).is_dir() {
                // .varg:29
                println!(
                    "{}",
                    format!("  {}OK{}    home is a directory", green, reset)
                );
            } else {
                // .varg:30
                println!(
                    "{}",
                    format!(
                        "  {}FAIL{}  home path does not point to a directory",
                        red, reset
                    )
                );
            }
        }
        // .varg:31
        let mut anthropic_key = std::env::var("ANTHROPIC_API_KEY".to_string()).unwrap_or_default();
        // .varg:32
        if anthropic_key == "".to_string() {
            // .varg:33
            println!(
                "{}",
                format!(
                    "  {}WARN{}  ANTHROPIC_API_KEY not set (LLM features unavailable)",
                    yellow, reset
                )
            );
        } else {
            // .varg:34
            println!(
                "{}",
                format!("  {}OK{}    ANTHROPIC_API_KEY is set", green, reset)
            );
        }
        // .varg:35
        let mut cwd = ".".to_string();
        // .varg:36
        if std::path::Path::new(&cwd).is_dir() {
            // .varg:37
            println!("{}", format!("  {}OK{}    cwd is accessible", green, reset));
        } else {
            // .varg:38
            println!(
                "{}",
                format!("  {}FAIL{}  cwd is not accessible", red, reset)
            );
        }
        // .varg:39
        println!("{}", "".to_string());
        // .varg:40
        println!("{}", "doctor complete.".to_string());
    }
    pub fn Colors(&mut self) {
        // .varg:41
        let mut reset = "\x1b[0m".to_string();
        // .varg:42
        let mut names = vec![
            "black".to_string(),
            "red".to_string(),
            "green".to_string(),
            "yellow".to_string(),
            "blue".to_string(),
            "magenta".to_string(),
            "cyan".to_string(),
            "white".to_string(),
            "gray".to_string(),
        ];
        // .varg:43
        println!(
            "{}",
            format!("{}ANSI color palette{}", "\x1b[1m".to_string(), reset)
        );
        // .varg:44
        println!("{}", "".to_string());
        // .varg:45
        for mut name in names {
            // .varg:46
            let mut color = (match name.as_str() {
                "black" => "\x1b[30m",
                "red" => "\x1b[31m",
                "green" => "\x1b[32m",
                "yellow" => "\x1b[33m",
                "blue" => "\x1b[34m",
                "magenta" => "\x1b[35m",
                "cyan" => "\x1b[36m",
                "white" => "\x1b[37m",
                "gray" | "grey" => "\x1b[90m",
                _ => "",
            })
            .to_string();
            // .varg:47
            println!("{}", format!("  {}██{} {}", color, reset, name));
        }
        // .varg:48
        println!("{}", "".to_string());
        // .varg:49
        println!(
            "{}",
            format!("  {}bold text{} (no color)", "\x1b[1m".to_string(), reset)
        );
    }
    pub fn Inspect(&mut self, path: String) {
        // .varg:50
        let mut bold = "\x1b[1m".to_string();
        // .varg:51
        let mut cyan = (match "cyan".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:52
        let mut reset = "\x1b[0m".to_string();
        // .varg:53
        println!("{}", format!("{}inspecting{} {}", bold, reset, path));
        // .varg:54
        println!("{}", "".to_string());
        // .varg:55
        if std::path::Path::new(&path).is_dir() {
            // .varg:56
            println!("{}", format!("  {}type{}     directory", cyan, reset));
        } else if std::path::Path::new(&path).is_file() {
            // .varg:57
            println!("{}", format!("  {}type{}     file", cyan, reset));
        } else {
            // .varg:58
            println!("{}", format!("  {}type{}     does not exist", cyan, reset));
            // .varg:59
            return;
        }
        // .varg:60
        println!(
            "{}",
            format!(
                "  {}parent{}   {}",
                cyan,
                reset,
                std::path::Path::new(&path)
                    .parent()
                    .map(|p| p.to_string_lossy().to_string())
                    .unwrap_or_default()
            )
        );
        // .varg:61
        unsafe {
            // .varg:62
            let mut resolved = std::fs::canonicalize(&path)
                .map(|p| p.to_string_lossy().to_string())
                .map_err(|e| e.to_string());
            // .varg:63
            match resolved {
                Ok(abs) => {
                    // .varg:64
                    println!("{}", format!("  {}absolute{} {}", cyan, reset, abs));
                }
                Err(e) => {
                    // .varg:65
                    println!("{}", format!("  {}absolute{} (error: {})", cyan, reset, e));
                }
            }
        }
    }
    pub fn Exec(&mut self, cmd: String, sys: SystemAccess) {
        // .varg:66
        let mut bold = "\x1b[1m".to_string();
        // .varg:67
        let mut dim = (match "gray".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:68
        let mut red = (match "red".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:69
        let mut green = (match "green".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:70
        let mut reset = "\x1b[0m".to_string();
        // .varg:71
        println!(
            "{}",
            format!("{}exec{} {}${} {}", bold, reset, dim, reset, cmd)
        );
        // .varg:72
        println!("{}", "".to_string());
        // .varg:73
        let mut spawned = varg_runtime::proc::__varg_proc_spawn(&cmd);
        // .varg:74
        match spawned {
            Err(e) => {
                // .varg:75
                println!("{}", format!("{}spawn failed:{} {}", red, reset, e));
                // .varg:76
                return;
            }
            Ok(handle) => {
                // .varg:77
                let mut line_count = 0;
                // .varg:78
                while true {
                    // .varg:79
                    let mut line_result = varg_runtime::proc::__varg_proc_read_line(&handle);
                    // .varg:80
                    match line_result {
                        Err(e) => {
                            // .varg:81
                            println!("{}", format!("{}read error:{} {}", red, reset, e));
                            // .varg:82
                            break;
                        }
                        Ok(line) => {
                            // .varg:83
                            if line == "".to_string() {
                                // .varg:84
                                break;
                            }
                            // .varg:85
                            println!("{}", format!("  {}", line));
                            // .varg:86
                            line_count += 1;
                        }
                    }
                }
                // .varg:87
                let mut code_result = varg_runtime::proc::__varg_proc_wait(&handle);
                // .varg:88
                match code_result {
                    Err(e) => {
                        // .varg:89
                        println!("{}", format!("{}wait error:{} {}", red, reset, e));
                    }
                    Ok(code) => {
                        // .varg:90
                        let mut color = green;
                        // .varg:91
                        if code != 0 {
                            // .varg:92
                            color = red;
                        }
                        // .varg:93
                        println!("{}", "".to_string());
                        // .varg:94
                        println!(
                            "{}",
                            format!("  {}exit{} {} ({} lines)", color, reset, code, line_count)
                        );
                    }
                }
            }
        }
    }
    pub fn Run(&mut self) {
        // .varg:95
        let mut argv = std::env::args().skip(1).collect::<Vec<String>>();
        // .varg:96
        if (argv.len() as i64) == 0 {
            // .varg:97
            self.PrintUsage();
            // .varg:98
            return;
        }
        // .varg:99
        let mut subcommand = argv[0 as usize].clone();
        // .varg:100
        if subcommand == "doctor".to_string() {
            // .varg:101
            self.Doctor();
            // .varg:102
            return;
        }
        // .varg:103
        if subcommand == "colors".to_string() {
            // .varg:104
            self.Colors();
            // .varg:105
            return;
        }
        // .varg:106
        if subcommand == "inspect".to_string() {
            // .varg:107
            if (argv.len() as i64) < 2 {
                // .varg:108
                println!("{}", "usage: claw_lite inspect <path>".to_string());
                // .varg:109
                return;
            }
            // .varg:110
            self.Inspect(argv[1 as usize].clone());
            // .varg:111
            return;
        }
        // .varg:112
        let mut sys = SystemAccess {};
        // .varg:113
        if subcommand == "exec".to_string() {
            // .varg:114
            return;
        }
        // .varg:115
        println!("{}", format!("unknown subcommand: {}", subcommand));
        // .varg:116
        println!("{}", "".to_string());
        // .varg:117
        self.PrintUsage();
    }
}
