#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

trait __VargFmt {
    fn __varg_fmt(&self) -> String;
}
macro_rules! __varg_fmt_display { ($($t:ty),*) => { $(impl __VargFmt for $t { fn __varg_fmt(&self) -> String { self.to_string() } })* } }
__varg_fmt_display!(
    String, bool, i8, i16, i32, i64, i128, u8, u16, u32, u64, u128, usize, isize, f32, f64
);
impl __VargFmt for &str {
    fn __varg_fmt(&self) -> String {
        self.to_string()
    }
}
impl<T: std::fmt::Debug> __VargFmt for Vec<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<K: std::fmt::Debug, V: std::fmt::Debug> __VargFmt for std::collections::HashMap<K, V> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<T: std::fmt::Debug> __VargFmt for std::collections::HashSet<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug> __VargFmt for (A, B) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug, C: std::fmt::Debug> __VargFmt for (A, B, C) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}

struct ClawLite {}

impl ClawLite {
    pub fn PrintUsage(&mut self) {
        // .varg:1
        let mut bold = "\x1b[1m".to_string();
        // .varg:2
        let mut cyan = (match "cyan".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:3
        let mut reset = "\x1b[0m".to_string();
        // .varg:4
        println!(
            "{}",
            format!(
                "{}claw_lite{} — tiny CLI agent harness in Varg",
                (bold).__varg_fmt(),
                (reset).__varg_fmt()
            )
        );
        // .varg:5
        println!("{}", "".to_string());
        // .varg:6
        println!(
            "{}",
            format!("{}USAGE{}", (cyan).__varg_fmt(), (reset).__varg_fmt())
        );
        // .varg:7
        println!("{}", "  claw_lite <subcommand> [args...]".to_string());
        // .varg:8
        println!("{}", "".to_string());
        // .varg:9
        println!(
            "{}",
            format!("{}SUBCOMMANDS{}", (cyan).__varg_fmt(), (reset).__varg_fmt())
        );
        // .varg:10
        println!(
            "{}",
            "  doctor          Check environment health".to_string()
        );
        // .varg:11
        println!(
            "{}",
            "  exec <cmd>      Spawn a subprocess and stream its stdout".to_string()
        );
        // .varg:12
        println!(
            "{}",
            "  colors          Show all ANSI color codes".to_string()
        );
        // .varg:13
        println!(
            "{}",
            "  inspect <path>  Inspect a filesystem path".to_string()
        );
    }
    pub fn Doctor(&mut self) {
        // .varg:14
        let mut bold = "\x1b[1m".to_string();
        // .varg:15
        let mut green = (match "green".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:16
        let mut red = (match "red".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:17
        let mut yellow = (match "yellow".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:18
        let mut reset = "\x1b[0m".to_string();
        // .varg:19
        println!(
            "{}",
            format!(
                "{}claw_lite doctor{}",
                (bold).__varg_fmt(),
                (reset).__varg_fmt()
            )
        );
        // .varg:20
        println!("{}", "".to_string());
        // .varg:21
        let mut home = std::env::var("HOME".to_string()).unwrap_or_default();
        // .varg:22
        if home == "".to_string() {
            // .varg:23
            home = std::env::var("USERPROFILE".to_string()).unwrap_or_default();
        }
        // .varg:24
        if home == "".to_string() {
            // .varg:25
            println!(
                "{}",
                format!(
                    "  {}FAIL{}  no HOME or USERPROFILE in environment",
                    (red).__varg_fmt(),
                    (reset).__varg_fmt()
                )
            );
        } else {
            // .varg:26
            println!(
                "{}",
                format!(
                    "  {}OK{}    home directory: {}",
                    (green).__varg_fmt(),
                    (reset).__varg_fmt(),
                    (home).__varg_fmt()
                )
            );
        }
        // .varg:27
        if home != "".to_string() {
            // .varg:28
            if std::path::Path::new(&home).is_dir() {
                // .varg:29
                println!(
                    "{}",
                    format!(
                        "  {}OK{}    home is a directory",
                        (green).__varg_fmt(),
                        (reset).__varg_fmt()
                    )
                );
            } else {
                // .varg:30
                println!(
                    "{}",
                    format!(
                        "  {}FAIL{}  home path does not point to a directory",
                        (red).__varg_fmt(),
                        (reset).__varg_fmt()
                    )
                );
            }
        }
        // .varg:31
        let mut anthropic_key = std::env::var("ANTHROPIC_API_KEY".to_string()).unwrap_or_default();
        // .varg:32
        if anthropic_key == "".to_string() {
            // .varg:33
            println!(
                "{}",
                format!(
                    "  {}WARN{}  ANTHROPIC_API_KEY not set (LLM features unavailable)",
                    (yellow).__varg_fmt(),
                    (reset).__varg_fmt()
                )
            );
        } else {
            // .varg:34
            println!(
                "{}",
                format!(
                    "  {}OK{}    ANTHROPIC_API_KEY is set",
                    (green).__varg_fmt(),
                    (reset).__varg_fmt()
                )
            );
        }
        // .varg:35
        let mut cwd = ".".to_string();
        // .varg:36
        if std::path::Path::new(&cwd).is_dir() {
            // .varg:37
            println!(
                "{}",
                format!(
                    "  {}OK{}    cwd is accessible",
                    (green).__varg_fmt(),
                    (reset).__varg_fmt()
                )
            );
        } else {
            // .varg:38
            println!(
                "{}",
                format!(
                    "  {}FAIL{}  cwd is not accessible",
                    (red).__varg_fmt(),
                    (reset).__varg_fmt()
                )
            );
        }
        // .varg:39
        println!("{}", "".to_string());
        // .varg:40
        println!("{}", "doctor complete.".to_string());
    }
    pub fn Colors(&mut self) {
        // .varg:41
        let mut reset = "\x1b[0m".to_string();
        // .varg:42
        let mut names = vec![
            "black".to_string(),
            "red".to_string(),
            "green".to_string(),
            "yellow".to_string(),
            "blue".to_string(),
            "magenta".to_string(),
            "cyan".to_string(),
            "white".to_string(),
            "gray".to_string(),
        ];
        // .varg:43
        println!(
            "{}",
            format!(
                "{}ANSI color palette{}",
                ("\x1b[1m".to_string()).__varg_fmt(),
                (reset).__varg_fmt()
            )
        );
        // .varg:44
        println!("{}", "".to_string());
        // .varg:45
        for mut name in names {
            // .varg:46
            let mut color = (match name.as_str() {
                "black" => "\x1b[30m",
                "red" => "\x1b[31m",
                "green" => "\x1b[32m",
                "yellow" => "\x1b[33m",
                "blue" => "\x1b[34m",
                "magenta" => "\x1b[35m",
                "cyan" => "\x1b[36m",
                "white" => "\x1b[37m",
                "gray" | "grey" => "\x1b[90m",
                _ => "",
            })
            .to_string();
            // .varg:47
            println!(
                "{}",
                format!(
                    "  {}██{} {}",
                    (color).__varg_fmt(),
                    (reset).__varg_fmt(),
                    (name).__varg_fmt()
                )
            );
        }
        // .varg:48
        println!("{}", "".to_string());
        // .varg:49
        println!(
            "{}",
            format!(
                "  {}bold text{} (no color)",
                ("\x1b[1m".to_string()).__varg_fmt(),
                (reset).__varg_fmt()
            )
        );
    }
    pub fn Inspect(&mut self, path: String) {
        // .varg:50
        let mut bold = "\x1b[1m".to_string();
        // .varg:51
        let mut cyan = (match "cyan".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:52
        let mut reset = "\x1b[0m".to_string();
        // .varg:53
        println!(
            "{}",
            format!(
                "{}inspecting{} {}",
                (bold).__varg_fmt(),
                (reset).__varg_fmt(),
                (path).__varg_fmt()
            )
        );
        // .varg:54
        println!("{}", "".to_string());
        // .varg:55
        if std::path::Path::new(&path).is_dir() {
            // .varg:56
            println!(
                "{}",
                format!(
                    "  {}type{}     directory",
                    (cyan).__varg_fmt(),
                    (reset).__varg_fmt()
                )
            );
        } else if std::path::Path::new(&path).is_file() {
            // .varg:57
            println!(
                "{}",
                format!(
                    "  {}type{}     file",
                    (cyan).__varg_fmt(),
                    (reset).__varg_fmt()
                )
            );
        } else {
            // .varg:58
            println!(
                "{}",
                format!(
                    "  {}type{}     does not exist",
                    (cyan).__varg_fmt(),
                    (reset).__varg_fmt()
                )
            );
            // .varg:59
            return;
        }
        // .varg:60
        println!(
            "{}",
            format!(
                "  {}parent{}   {}",
                (cyan).__varg_fmt(),
                (reset).__varg_fmt(),
                (std::path::Path::new(&path)
                    .parent()
                    .map(|p| p.to_string_lossy().to_string())
                    .unwrap_or_default())
                .__varg_fmt()
            )
        );
        // .varg:61
        unsafe {
            // .varg:62
            let mut resolved = std::fs::canonicalize(&path)
                .map(|p| p.to_string_lossy().to_string())
                .map_err(|e| e.to_string());
            // .varg:63
            match resolved {
                Ok(abs) => {
                    // .varg:64
                    println!(
                        "{}",
                        format!(
                            "  {}absolute{} {}",
                            (cyan).__varg_fmt(),
                            (reset).__varg_fmt(),
                            (abs).__varg_fmt()
                        )
                    );
                }
                Err(e) => {
                    // .varg:65
                    println!(
                        "{}",
                        format!(
                            "  {}absolute{} (error: {})",
                            (cyan).__varg_fmt(),
                            (reset).__varg_fmt(),
                            (e).__varg_fmt()
                        )
                    );
                }
            }
        }
    }
    pub fn Exec(&mut self, cmd: String, sys: SystemAccess) {
        // .varg:66
        let mut bold = "\x1b[1m".to_string();
        // .varg:67
        let mut dim = (match "gray".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:68
        let mut red = (match "red".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:69
        let mut green = (match "green".to_string().as_str() {
            "black" => "\x1b[30m",
            "red" => "\x1b[31m",
            "green" => "\x1b[32m",
            "yellow" => "\x1b[33m",
            "blue" => "\x1b[34m",
            "magenta" => "\x1b[35m",
            "cyan" => "\x1b[36m",
            "white" => "\x1b[37m",
            "gray" | "grey" => "\x1b[90m",
            _ => "",
        })
        .to_string();
        // .varg:70
        let mut reset = "\x1b[0m".to_string();
        // .varg:71
        println!(
            "{}",
            format!(
                "{}exec{} {}${} {}",
                (bold).__varg_fmt(),
                (reset).__varg_fmt(),
                (dim).__varg_fmt(),
                (reset).__varg_fmt(),
                (cmd).__varg_fmt()
            )
        );
        // .varg:72
        println!("{}", "".to_string());
        // .varg:73
        let mut spawned = varg_runtime::proc::__varg_proc_spawn(&cmd);
        // .varg:74
        match spawned {
            Err(e) => {
                // .varg:75
                println!(
                    "{}",
                    format!(
                        "{}spawn failed:{} {}",
                        (red).__varg_fmt(),
                        (reset).__varg_fmt(),
                        (e).__varg_fmt()
                    )
                );
                // .varg:76
                return;
            }
            Ok(handle) => {
                // .varg:77
                let mut line_count = 0;
                // .varg:78
                while true {
                    // .varg:79
                    let mut line_result = varg_runtime::proc::__varg_proc_read_line(&handle);
                    // .varg:80
                    match line_result {
                        Err(e) => {
                            // .varg:81
                            println!(
                                "{}",
                                format!(
                                    "{}read error:{} {}",
                                    (red).__varg_fmt(),
                                    (reset).__varg_fmt(),
                                    (e).__varg_fmt()
                                )
                            );
                            // .varg:82
                            break;
                        }
                        Ok(line) => {
                            // .varg:83
                            if line == "".to_string() {
                                // .varg:84
                                break;
                            }
                            // .varg:85
                            println!("{}", format!("  {}", (line).__varg_fmt()));
                            // .varg:86
                            line_count += 1;
                        }
                    }
                }
                // .varg:87
                let mut code_result = varg_runtime::proc::__varg_proc_wait(&handle);
                // .varg:88
                match code_result {
                    Err(e) => {
                        // .varg:89
                        println!(
                            "{}",
                            format!(
                                "{}wait error:{} {}",
                                (red).__varg_fmt(),
                                (reset).__varg_fmt(),
                                (e).__varg_fmt()
                            )
                        );
                    }
                    Ok(code) => {
                        // .varg:90
                        let mut color = green;
                        // .varg:91
                        if code != 0 {
                            // .varg:92
                            color = red;
                        }
                        // .varg:93
                        println!("{}", "".to_string());
                        // .varg:94
                        println!(
                            "{}",
                            format!(
                                "  {}exit{} {} ({} lines)",
                                (color).__varg_fmt(),
                                (reset).__varg_fmt(),
                                (code).__varg_fmt(),
                                (line_count).__varg_fmt()
                            )
                        );
                    }
                }
            }
        }
    }
    pub fn Run(&mut self) {
        // .varg:95
        let mut argv = std::env::args().skip(1).collect::<Vec<String>>();
        // .varg:96
        if (argv.len() as i64) == 0 {
            // .varg:97
            self.PrintUsage();
            // .varg:98
            return;
        }
        // .varg:99
        let mut subcommand = argv[(0) as usize].clone();
        // .varg:100
        if subcommand == "doctor".to_string() {
            // .varg:101
            self.Doctor();
            // .varg:102
            return;
        }
        // .varg:103
        if subcommand == "colors".to_string() {
            // .varg:104
            self.Colors();
            // .varg:105
            return;
        }
        // .varg:106
        if subcommand == "inspect".to_string() {
            // .varg:107
            if (argv.len() as i64) < 2 {
                // .varg:108
                println!("{}", "usage: claw_lite inspect <path>".to_string());
                // .varg:109
                return;
            }
            // .varg:110
            self.Inspect(argv[(1) as usize].clone());
            // .varg:111
            return;
        }
        // .varg:112
        if subcommand == "exec".to_string() {
            // .varg:113
            if (argv.len() as i64) < 2 {
                // .varg:114
                println!("{}", "usage: claw_lite exec <cmd>".to_string());
                // .varg:115
                return;
            }
            // .varg:116
            unsafe {
                // .varg:117
                let mut sys = SystemAccess {};
                // .varg:118
                self.Exec(argv[(1) as usize].clone(), sys);
            }
            // .varg:119
            return;
        }
        // .varg:120
        println!(
            "{}",
            format!("unknown subcommand: {}", (subcommand).__varg_fmt())
        );
        // .varg:121
        println!("{}", "".to_string());
        // .varg:122
        self.PrintUsage();
    }
}
