#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

trait __VargFmt {
    fn __varg_fmt(&self) -> String;
}
macro_rules! __varg_fmt_display { ($($t:ty),*) => { $(impl __VargFmt for $t { fn __varg_fmt(&self) -> String { self.to_string() } })* } }
__varg_fmt_display!(
    String, bool, i8, i16, i32, i64, i128, u8, u16, u32, u64, u128, usize, isize, f32, f64
);
impl __VargFmt for &str {
    fn __varg_fmt(&self) -> String {
        self.to_string()
    }
}
impl<T: std::fmt::Debug> __VargFmt for Vec<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<K: std::fmt::Debug, V: std::fmt::Debug> __VargFmt for std::collections::HashMap<K, V> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<T: std::fmt::Debug> __VargFmt for std::collections::HashSet<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug> __VargFmt for (A, B) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug, C: std::fmt::Debug> __VargFmt for (A, B, C) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}

struct FileProcessor {
    pub files_processed: i64,
}

impl FileProcessor {
    pub fn new() -> Self {
        let mut __self = FileProcessor { files_processed: 0 };
        __self
    }
    pub fn on_start(&mut self) {
        // .varg:1
        self.files_processed = 0;
    }
    pub fn CountWords(&mut self, path: String, cap: FileAccess) -> Result<i64, String> {
        // .varg:2
        let mut content = (std::fs::read_to_string(&path).map_err(|e| e.to_string()))?;
        // .varg:3
        let mut words = content
            .split(&" ".to_string())
            .map(|s| s.to_string())
            .collect::<Vec<String>>();
        // .varg:4
        return Ok((words.len() as i64));
        Ok(())
    }
    pub fn ProcessDirectory(&mut self, dir: String, cap: FileAccess) {
        // .varg:5
        let mut files = (std::fs::read_dir(&dir)
            .map_err(|e| e.to_string())
            .map(|entries| {
                entries
                    .filter_map(|e| e.ok())
                    .map(|e| e.path().to_string_lossy().to_string())
                    .collect::<Vec<String>>()
            }))
        .unwrap_or_else(|_| vec![]);
        // .varg:6
        for mut file in files {
            // .varg:7
            if file.ends_with(&".txt".to_string()) {
                // .varg:8
                #[allow(unreachable_code, unused_labels)]
                let _varg_try_res: std::result::Result<(), String> = 'varg_try: {
                    // .varg:9
                    let mut count = self.CountWords(file, cap);
                    // .varg:10
                    println!(
                        "[INFO] {}",
                        format!("{}: {} words", (file).__varg_fmt(), (count).__varg_fmt())
                    );
                    // .varg:11
                    self.files_processed += 1;
                    Ok(())
                };
                if let Err(mut err) = _varg_try_res {
                    // .varg:12
                    eprintln!(
                        "[WARN] {}",
                        format!("Skipping {}: {}", (file).__varg_fmt(), (err).__varg_fmt())
                    );
                }
            }
        }
    }
    pub fn Run(&mut self) {
        // .varg:13
        println!("[INFO] {}", "File Processor starting...".to_string());
        // .varg:14
        unsafe {
            // .varg:15
            let mut cap = FileAccess {};
            // .varg:16
            self.ProcessDirectory(".".to_string(), cap);
        }
        // .varg:17
        println!(
            "[INFO] {}",
            format!(
                "Done. Processed {} files.",
                (self.files_processed).__varg_fmt()
            )
        );
    }
}
