#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

struct Hello {}

impl Hello {
    pub fn Run(&mut self) {
        // .varg:1
        println!("{}", "Hello from Varg!".to_string());
        // .varg:2
        println!(
            "{}",
            format!("Built at: {}", chrono::Local::now().to_rfc3339())
        );
    }
}
