#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

trait __VargFmt {
    fn __varg_fmt(&self) -> String;
}
macro_rules! __varg_fmt_display { ($($t:ty),*) => { $(impl __VargFmt for $t { fn __varg_fmt(&self) -> String { self.to_string() } })* } }
__varg_fmt_display!(
    String, bool, i8, i16, i32, i64, i128, u8, u16, u32, u64, u128, usize, isize, f32, f64
);
impl __VargFmt for &str {
    fn __varg_fmt(&self) -> String {
        self.to_string()
    }
}
impl<T: std::fmt::Debug> __VargFmt for Vec<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<K: std::fmt::Debug, V: std::fmt::Debug> __VargFmt for std::collections::HashMap<K, V> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<T: std::fmt::Debug> __VargFmt for std::collections::HashSet<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug> __VargFmt for (A, B) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug, C: std::fmt::Debug> __VargFmt for (A, B, C) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}

fn main() {
    // .varg:1
    let mut g = varg_runtime::graph::__varg_graph_open(&"team_graph".to_string());
    // .varg:2
    let mut alice = varg_runtime::graph::__varg_graph_add_node(
        &g,
        &"Person".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Alice".to_string()),
            ("role".to_string(), "Engineer".to_string()),
        ]),
    );
    // .varg:3
    let mut bob = varg_runtime::graph::__varg_graph_add_node(
        &g,
        &"Person".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Bob".to_string()),
            ("role".to_string(), "Designer".to_string()),
        ]),
    );
    // .varg:4
    let mut charlie = varg_runtime::graph::__varg_graph_add_node(
        &g,
        &"Person".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Charlie".to_string()),
            ("role".to_string(), "PM".to_string()),
        ]),
    );
    // .varg:5
    let mut varg = varg_runtime::graph::__varg_graph_add_node(
        &g,
        &"Project".to_string(),
        &std::collections::HashMap::from([
            ("name".to_string(), "Varg".to_string()),
            ("status".to_string(), "active".to_string()),
        ]),
    );
    // .varg:6
    varg_runtime::graph::__varg_graph_add_edge(
        &g,
        alice,
        &"works_on".to_string(),
        varg,
        &std::collections::HashMap::from([]),
    );
    // .varg:7
    varg_runtime::graph::__varg_graph_add_edge(
        &g,
        bob,
        &"works_on".to_string(),
        varg,
        &std::collections::HashMap::from([]),
    );
    // .varg:8
    varg_runtime::graph::__varg_graph_add_edge(
        &g,
        alice,
        &"knows".to_string(),
        bob,
        &std::collections::HashMap::from([]),
    );
    // .varg:9
    varg_runtime::graph::__varg_graph_add_edge(
        &g,
        bob,
        &"knows".to_string(),
        charlie,
        &std::collections::HashMap::from([]),
    );
    // .varg:10
    let mut people = varg_runtime::graph::__varg_graph_query(&g, &"Person".to_string());
    // .varg:11
    println!(
        "{}",
        format!("People: {}", (people.len() as i64).__varg_fmt())
    );
    // .varg:12
    let mut projects = varg_runtime::graph::__varg_graph_query(&g, &"Project".to_string());
    // .varg:13
    println!(
        "{}",
        format!("Projects: {}", (projects.len() as i64).__varg_fmt())
    );
    // .varg:14
    let mut one_hop =
        varg_runtime::graph::__varg_graph_traverse(&g, alice, 1, &"knows".to_string());
    // .varg:15
    println!(
        "{}",
        format!(
            "Alice knows (1 hop): {}",
            (one_hop.len() as i64).__varg_fmt()
        )
    );
    // .varg:16
    let mut two_hop =
        varg_runtime::graph::__varg_graph_traverse(&g, alice, 2, &"knows".to_string());
    // .varg:17
    println!(
        "{}",
        format!(
            "Alice knows (2 hops): {}",
            (two_hop.len() as i64).__varg_fmt()
        )
    );
    // .varg:18
    let mut bob_neighbors = varg_runtime::graph::__varg_graph_neighbors(&g, bob);
    // .varg:19
    println!(
        "{}",
        format!(
            "Bob neighbors: {}",
            (bob_neighbors.len() as i64).__varg_fmt()
        )
    );
    // .varg:20
    println!("{}", "Knowledge graph demo complete!".to_string());
}
