#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

fn main() {
    // .varg:1
    let mut tracer = varg_runtime::trace::__varg_trace_start(&"order_processor".to_string());
    // .varg:2
    let mut s1 = varg_runtime::trace::__varg_trace_span(&tracer, &"process_order".to_string());
    // .varg:3
    varg_runtime::trace::__varg_trace_set_attr(
        &tracer,
        &"order_id".to_string(),
        &"ORD-42".to_string(),
    );
    // .varg:4
    let mut s2 = varg_runtime::trace::__varg_trace_span(&tracer, &"validate_input".to_string());
    // .varg:5
    varg_runtime::trace::__varg_trace_event(
        &tracer,
        &"validation_passed".to_string(),
        &std::collections::HashMap::from([("fields".to_string(), "3".to_string())]),
    );
    // .varg:6
    varg_runtime::trace::__varg_trace_end(&tracer, s2);
    // .varg:7
    let mut s3 = varg_runtime::trace::__varg_trace_span(&tracer, &"db_write".to_string());
    // .varg:8
    varg_runtime::trace::__varg_trace_set_attr(
        &tracer,
        &"db.system".to_string(),
        &"sqlite".to_string(),
    );
    // .varg:9
    varg_runtime::trace::__varg_trace_error(&tracer, s3, &"connection timeout".to_string());
    // .varg:10
    varg_runtime::trace::__varg_trace_end(&tracer, s1);
    // .varg:11
    println!(
        "{}",
        format!(
            "Total spans: {}",
            varg_runtime::trace::__varg_trace_span_count(&tracer)
        )
    );
    // .varg:12
    let mut json = varg_runtime::trace::__varg_trace_export(&tracer);
    // .varg:13
    println!("{}", format!("Trace JSON length: {}", json.len() as i64));
    // .varg:14
    println!("{}", "Tracing demo complete!".to_string());
}
