#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

trait __VargFmt {
    fn __varg_fmt(&self) -> String;
}
macro_rules! __varg_fmt_display { ($($t:ty),*) => { $(impl __VargFmt for $t { fn __varg_fmt(&self) -> String { self.to_string() } })* } }
__varg_fmt_display!(
    String, bool, i8, i16, i32, i64, i128, u8, u16, u32, u64, u128, usize, isize, f32, f64
);
impl __VargFmt for &str {
    fn __varg_fmt(&self) -> String {
        self.to_string()
    }
}
impl<T: std::fmt::Debug> __VargFmt for Vec<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<K: std::fmt::Debug, V: std::fmt::Debug> __VargFmt for std::collections::HashMap<K, V> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<T: std::fmt::Debug> __VargFmt for std::collections::HashSet<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug> __VargFmt for (A, B) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug, C: std::fmt::Debug> __VargFmt for (A, B, C) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}

fn main() {
    // .varg:1
    let mut tracer = varg_runtime::trace::__varg_trace_start(&"order_processor".to_string());
    // .varg:2
    let mut s1 = varg_runtime::trace::__varg_trace_span(&tracer, &"process_order".to_string());
    // .varg:3
    varg_runtime::trace::__varg_trace_set_attr(
        &tracer,
        &"order_id".to_string(),
        &"ORD-42".to_string(),
    );
    // .varg:4
    let mut s2 = varg_runtime::trace::__varg_trace_span(&tracer, &"validate_input".to_string());
    // .varg:5
    varg_runtime::trace::__varg_trace_event(
        &tracer,
        &"validation_passed".to_string(),
        &std::collections::HashMap::from([("fields".to_string(), "3".to_string())]),
    );
    // .varg:6
    varg_runtime::trace::__varg_trace_end(&tracer, s2);
    // .varg:7
    let mut s3 = varg_runtime::trace::__varg_trace_span(&tracer, &"db_write".to_string());
    // .varg:8
    varg_runtime::trace::__varg_trace_set_attr(
        &tracer,
        &"db.system".to_string(),
        &"sqlite".to_string(),
    );
    // .varg:9
    varg_runtime::trace::__varg_trace_error(&tracer, s3, &"connection timeout".to_string());
    // .varg:10
    varg_runtime::trace::__varg_trace_end(&tracer, s1);
    // .varg:11
    println!(
        "{}",
        format!(
            "Total spans: {}",
            (varg_runtime::trace::__varg_trace_span_count(&tracer)).__varg_fmt()
        )
    );
    // .varg:12
    let mut json = varg_runtime::trace::__varg_trace_export(&tracer);
    // .varg:13
    println!(
        "{}",
        format!("Trace JSON length: {}", (json.len() as i64).__varg_fmt())
    );
    // .varg:14
    println!("{}", "Tracing demo complete!".to_string());
}
