#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

fn main() {
    // .varg:1
    let mut store = varg_runtime::vector::__varg_vector_store_open(&"documents".to_string());
    // .varg:2
    let mut e1 =
        varg_runtime::vector::__varg_embed(&"Alice works on the Varg compiler project".to_string());
    // .varg:3
    let mut e2 =
        varg_runtime::vector::__varg_embed(&"Bob designs the user interface for Varg".to_string());
    // .varg:4
    let mut e3 =
        varg_runtime::vector::__varg_embed(&"Quantum physics and string theory".to_string());
    // .varg:5
    varg_runtime::vector::__varg_vector_store_upsert(
        &store,
        &"doc1".to_string(),
        &e1,
        &std::collections::HashMap::from([
            ("source".to_string(), "chat".to_string()),
            ("author".to_string(), "Alice".to_string()),
        ]),
    );
    // .varg:6
    varg_runtime::vector::__varg_vector_store_upsert(
        &store,
        &"doc2".to_string(),
        &e2,
        &std::collections::HashMap::from([
            ("source".to_string(), "chat".to_string()),
            ("author".to_string(), "Bob".to_string()),
        ]),
    );
    // .varg:7
    varg_runtime::vector::__varg_vector_store_upsert(
        &store,
        &"doc3".to_string(),
        &e3,
        &std::collections::HashMap::from([
            ("source".to_string(), "paper".to_string()),
            ("author".to_string(), "Eve".to_string()),
        ]),
    );
    // .varg:8
    println!(
        "{}",
        format!(
            "Documents stored: {}",
            varg_runtime::vector::__varg_vector_store_count(&store)
        )
    );
    // .varg:9
    let mut search_vec = varg_runtime::vector::__varg_embed(&"Who works on Varg?".to_string());
    // .varg:10
    let mut results = varg_runtime::vector::__varg_vector_store_search(&store, &search_vec, 2);
    // .varg:11
    println!("{}", format!("Search results: {}", results.len() as i64));
    // .varg:12
    varg_runtime::vector::__varg_vector_store_delete(&store, &"doc3".to_string());
    // .varg:13
    println!(
        "{}",
        format!(
            "After delete: {}",
            varg_runtime::vector::__varg_vector_store_count(&store)
        )
    );
    // .varg:14
    println!("{}", "Vector store demo complete!".to_string());
}
