#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

struct BytesTest {}

impl BytesTest {
    pub fn Run(&mut self) {
        // .varg:1
        unsafe {
            // .varg:2
            let mut cap = FileAccess {};
            // .varg:3
            let mut path = "target/wave29_test.bin".to_string();
            // .varg:4
            let mut bytes = vec![72, 101, 108, 108, 111, 44, 32, 66, 121, 116, 101, 115, 33];
            // .varg:5
            let mut written = ({
                let __varg_bytes: Vec<u8> = bytes.iter().map(|b: &i64| *b as u8).collect();
                std::fs::write(path, &__varg_bytes)
                    .map(|_| __varg_bytes.len() as i64)
                    .map_err(|e| e.to_string())
            })
            .unwrap_or_else(|_| 0);
            // .varg:6
            println!("{}", format!("wrote {} bytes to {}", written, path));
            // .varg:7
            let mut size = (std::fs::metadata(path)
                .map(|m| m.len() as i64)
                .map_err(|e| e.to_string()))
            .unwrap_or_else(|_| 0);
            // .varg:8
            println!("{}", format!("size: {}", size));
            // .varg:9
            let mut read = (std::fs::read(path)
                .map(|v| v.into_iter().map(|b| b as i64).collect::<Vec<i64>>())
                .map_err(|e| e.to_string()))
            .unwrap_or_else(|_| vec![]);
            // .varg:10
            println!("{}", format!("read {} bytes", (read.len() as i64)));
            // .varg:11
            println!("{}", format!("first byte: {}", read[0 as usize].clone()));
            // .varg:12
            println!(
                "{}",
                format!(
                    "last byte: {}",
                    read[(read.len() as i64) - 1 as usize].clone()
                )
            );
            // .varg:13
            let mut appended = ({
                let __varg_bytes: Vec<u8> = vec![10, 33].iter().map(|b: &i64| *b as u8).collect();
                std::fs::OpenOptions::new()
                    .append(true)
                    .create(true)
                    .open(path)
                    .and_then(|mut f| {
                        use std::io::Write;
                        f.write_all(&__varg_bytes)
                            .map(|_| __varg_bytes.len() as i64)
                    })
                    .map_err(|e| e.to_string())
            })
            .unwrap_or_else(|_| 0);
            // .varg:14
            println!("{}", format!("appended {} bytes", appended));
            // .varg:15
            let mut final_size = (std::fs::metadata(path)
                .map(|m| m.len() as i64)
                .map_err(|e| e.to_string()))
            .unwrap_or_else(|_| 0);
            // .varg:16
            println!("{}", format!("final size: {}", final_size));
        }
    }
}
