#![allow(
    unused_variables,
    unused_mut,
    dead_code,
    unused_imports,
    unreachable_code,
    unused_assignments
)]

// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;
use varg_runtime::*;

trait __VargFmt {
    fn __varg_fmt(&self) -> String;
}
macro_rules! __varg_fmt_display { ($($t:ty),*) => { $(impl __VargFmt for $t { fn __varg_fmt(&self) -> String { self.to_string() } })* } }
__varg_fmt_display!(
    String, bool, i8, i16, i32, i64, i128, u8, u16, u32, u64, u128, usize, isize, f32, f64
);
impl __VargFmt for &str {
    fn __varg_fmt(&self) -> String {
        self.to_string()
    }
}
impl<T: std::fmt::Debug> __VargFmt for Vec<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<K: std::fmt::Debug, V: std::fmt::Debug> __VargFmt for std::collections::HashMap<K, V> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<T: std::fmt::Debug> __VargFmt for std::collections::HashSet<T> {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug> __VargFmt for (A, B) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}
impl<A: std::fmt::Debug, B: std::fmt::Debug, C: std::fmt::Debug> __VargFmt for (A, B, C) {
    fn __varg_fmt(&self) -> String {
        format!("{:?}", self)
    }
}

struct BytesTest {}

impl BytesTest {
    pub fn Run(&mut self) {
        // .varg:1
        unsafe {
            // .varg:2
            let mut cap = FileAccess {};
            // .varg:3
            let mut path = "target/wave29_test.bin".to_string();
            // .varg:4
            let mut bytes = vec![72, 101, 108, 108, 111, 44, 32, 66, 121, 116, 101, 115, 33];
            // .varg:5
            let mut written = ({
                let __varg_bytes: Vec<u8> = bytes.iter().map(|b: &i64| *b as u8).collect();
                std::fs::write(&path, &__varg_bytes)
                    .map(|_| __varg_bytes.len() as i64)
                    .map_err(|e| e.to_string())
            })
            .unwrap_or_else(|_| 0);
            // .varg:6
            println!("{}", format!("wrote {} bytes", (written).__varg_fmt()));
            // .varg:7
            let mut size = (std::fs::metadata(&path)
                .map(|m| m.len() as i64)
                .map_err(|e| e.to_string()))
            .unwrap_or_else(|_| 0);
            // .varg:8
            println!("{}", format!("size: {}", (size).__varg_fmt()));
            // .varg:9
            let mut read = (std::fs::read(&path)
                .map(|v| v.into_iter().map(|b| b as i64).collect::<Vec<i64>>())
                .map_err(|e| e.to_string()))
            .unwrap_or_else(|_| vec![]);
            // .varg:10
            println!(
                "{}",
                format!("read {} bytes", (read.len() as i64).__varg_fmt())
            );
            // .varg:11
            println!(
                "{}",
                format!("first byte: {}", (read[(0) as usize].clone()).__varg_fmt())
            );
            // .varg:12
            println!(
                "{}",
                format!(
                    "last byte: {}",
                    (read[((read.len() as i64) - 1) as usize].clone()).__varg_fmt()
                )
            );
            // .varg:13
            let mut appended = ({
                let __varg_bytes: Vec<u8> = vec![10, 33].iter().map(|b: &i64| *b as u8).collect();
                std::fs::OpenOptions::new()
                    .append(true)
                    .create(true)
                    .open(&path)
                    .and_then(|mut f| {
                        use std::io::Write;
                        f.write_all(&__varg_bytes)
                            .map(|_| __varg_bytes.len() as i64)
                    })
                    .map_err(|e| e.to_string())
            })
            .unwrap_or_else(|_| 0);
            // .varg:14
            println!("{}", format!("appended {} bytes", (appended).__varg_fmt()));
            // .varg:15
            let mut final_size = (std::fs::metadata(&path)
                .map(|m| m.len() as i64)
                .map_err(|e| e.to_string()))
            .unwrap_or_else(|_| 0);
            // .varg:16
            println!("{}", format!("final size: {}", (final_size).__varg_fmt()));
        }
    }
}
