// --- AUTOGENERATED BY Varg Compiler ---
use varg_os_types::*;

// --- varg CRYPTO CORE ---
use aes_gcm::{aead::{Aead, KeyInit, OsRng}, Aes256Gcm, Nonce};
use pbkdf2::pbkdf2_hmac;
use sha2::Sha512;
use rand::RngCore;
use base64::{engine::general_purpose::STANDARD, Engine as _};

fn __varg_derive_key(key: &str, salt: &[u8]) -> [u8; 32] {
    let mut derived_key = [0u8; 32];
    pbkdf2_hmac::<Sha512>(key.as_bytes(), salt, 600_000, &mut derived_key);
    derived_key
}

fn __varg_encrypt(data: &str, key: &str) -> String {
    let mut salt = [0u8; 16];
    OsRng.fill_bytes(&mut salt);
    let derived_key = __varg_derive_key(key, &salt);
    let cipher = Aes256Gcm::new_from_slice(&derived_key).unwrap();
    let mut nonce_bytes = [0u8; 12];
    OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);
    let ciphertext = cipher.encrypt(nonce, data.as_bytes()).expect("[VargOS] Encryption failed");
    let mut packed = Vec::with_capacity(16 + 12 + ciphertext.len());
    packed.extend_from_slice(&salt);
    packed.extend_from_slice(&nonce_bytes);
    packed.extend_from_slice(&ciphertext);
    STANDARD.encode(packed)
}

fn __varg_decrypt(data: &str, key: &str) -> String {
    let packed = STANDARD.decode(data).expect("[VargOS] Invalid Base64 Encryption Payload");
    if packed.len() < 16 + 12 {
         panic!("[VargOS] Payload too short for AES-GCM.");
    }
    let salt = &packed[0..16];
    let nonce_bytes = &packed[16..28];
    let ciphertext = &packed[28..];
    let derived_key = __varg_derive_key(key, salt);
    let cipher = Aes256Gcm::new_from_slice(&derived_key).unwrap();
    let nonce = Nonce::from_slice(nonce_bytes);
    let plaintext = cipher.decrypt(nonce, ciphertext).expect("[VargOS] Decryption failed or wrong password");
    String::from_utf8(plaintext).unwrap()
}

// --- varg NETWORKING CORE ---
fn __varg_fetch(url: &str, method: &str, headers: std::collections::HashMap<String, String>, body: &str) -> String {
    let mut cmd = std::process::Command::new("curl");
    cmd.arg("-s").arg("-X").arg(method);
    for (k, v) in headers {
        cmd.arg("-H").arg(format!("{}: {}", k, v));
    }
    if !body.is_empty() {
        cmd.arg("-d").arg(body);
    }
    cmd.arg(url);
    match cmd.output() {
        Ok(output) if output.status.success() => String::from_utf8_lossy(&output.stdout).to_string(),
        Ok(output) => format!("{{ \"error\": \"Request Failed: {}\" }}", String::from_utf8_lossy(&output.stderr)),
        Err(e) => format!("{{ \"error\": \"Network Exec Error: {}\" }}", e),
    }
}

// --- varg EMBEDDED KV DATABASE (Phase 15) ---
fn __varg_query(query: &str) -> String {
    let db_path = ".varg_memory.json";
    let mut db: std::collections::HashMap<String, String> = std::fs::read_to_string(db_path).ok().and_then(|s| serde_json::from_str(&s).ok()).unwrap_or_default();
    let parts: Vec<&str> = query.split_whitespace().collect();
    if parts.is_empty() { return "[]".to_string(); }
    let cmd = parts[0].to_uppercase();
    if cmd == "SET" && parts.len() >= 3 {
        let key = parts[1];
        let val = parts[2..].join(" ");
        db.insert(key.to_string(), val);
        let _ = std::fs::write(db_path, serde_json::to_string(&db).unwrap());
        return "{\"status\": \"ok\"}".to_string();
    } else if cmd == "GET" && parts.len() == 2 {
        let key = parts[1];
        if let Some(val) = db.get(key) {
            // Attempt to parse val as JSON. If not JSON, return as string.
            if serde_json::from_str::<serde_json::Value>(val).is_ok() {
                return val.to_string();
            } else {
                return format!("\"{}\"", val.replace("\"", "\\\""));
            }
        } else {
            return "null".to_string();
        }
    }
    serde_json::to_string(&db).unwrap_or_else(|_| "{}".to_string())
}

// --- varg AUTONOMOUS LLM ENGINE (Phase 16) ---
fn __varg_llm_infer(prompt: &str, model: &str) -> String {
    let mut headers = std::collections::HashMap::new();
    headers.insert("Content-Type".to_string(), "application/json".to_string());
    let safe_prompt = prompt.replace("\"", "\\\"\n");
    let body = format!("{{\"model\": \"{}\", \"messages\": [{{\"role\": \"user\", \"content\": \"{}\"}}], \"stream\": false}}", model, safe_prompt);
    let res = __varg_fetch("http://127.0.0.1:11434/api/chat", "POST", headers, &body);
    if let Ok(json) = serde_json::from_str::<serde_json::Value>(&res) {
        if let Some(content) = json.get("message").and_then(|m| m.get("content")).and_then(|c| c.as_str()) {
            return content.to_string();
        }
    }
    res
}

fn __varg_fetch_stream(url: &str, method: &str, headers: std::collections::HashMap<String, String>, body: &str) {
    let mut cmd = std::process::Command::new("curl");
    cmd.arg("-N").arg("-s").arg("-X").arg(method);
    for (k, v) in headers {
        cmd.arg("-H").arg(format!("{}: {}", k, v));
    }
    if !body.is_empty() { cmd.arg("-d").arg(body); }
    cmd.arg(url);
    if let Ok(mut child) = cmd.stdout(std::process::Stdio::piped()).spawn() {
        if let Some(stdout) = child.stdout.take() {
            use std::io::{BufRead, BufReader, Write};
            for line in BufReader::new(stdout).lines().filter_map(Result::ok) {
                if let Ok(json) = serde_json::from_str::<serde_json::Value>(&line) {
                    if let Some(content) = json.get("message").and_then(|m| m.get("content")).and_then(|c| c.as_str()) {
                        print!("{}", content); std::io::stdout().flush().unwrap();
                    }
                }
            }
        }
    }
    println!();
}

fn __varg_llm_chat_stream(ctx: &mut Context, prompt: &str, model: &str) {
    let mut headers = std::collections::HashMap::new();
    headers.insert("Content-Type".to_string(), "application/json".to_string());
    ctx.push("user", prompt);
    let messages_json = serde_json::to_string(&ctx.messages).unwrap_or_else(|_| "[]".to_string());
    let body = format!("{{\"model\": \"{}\", \"messages\": {}, \"stream\": true}}", model, messages_json);
    __varg_fetch_stream("http://127.0.0.1:11434/api/chat", "POST", headers, &body);
    ctx.push("assistant", "[STREAMED_REPLY]");
}

fn __varg_llm_infer_stream(prompt: &str, model: &str) {
    let mut headers = std::collections::HashMap::new();
    headers.insert("Content-Type".to_string(), "application/json".to_string());
    let safe_prompt = prompt.replace("\"", "\\\"\n");
    let body = format!("{{\"model\": \"{}\", \"messages\": [{{\"role\": \"user\", \"content\": \"{}\"}}], \"stream\": true}}", model, safe_prompt);
    __varg_fetch_stream("http://127.0.0.1:11434/api/chat", "POST", headers, &body);
}

fn __varg_create_context(id: &str) -> Context {
    Context::new(id)
}

fn __varg_context_from(data: &str) -> Context {
    let mut ctx = Context::new("rag_context");
    ctx.push("system", &format!("Use the following context to answer:\n{}", data));
    ctx
}

fn __varg_llm_chat(ctx: &mut Context, prompt: &str, model: &str) -> String {
    let mut headers = std::collections::HashMap::new();
    headers.insert("Content-Type".to_string(), "application/json".to_string());
    ctx.push("user", prompt);
    let messages_json = serde_json::to_string(&ctx.messages).unwrap_or_else(|_| "[]".to_string());
    let body = format!("{{\"model\": \"{}\", \"messages\": {}, \"stream\": false}}", model, messages_json);
    let res = __varg_fetch("http://127.0.0.1:11434/api/chat", "POST", headers, &body);
    if let Ok(json) = serde_json::from_str::<serde_json::Value>(&res) {
        if let Some(content) = json.get("message").and_then(|m| m.get("content")).and_then(|c| c.as_str()) {
            ctx.push("assistant", content);
            return content.to_string();
        }
    }
    res
}

// --- varg VECTOR MATH (Phase 20.B) ---
fn __varg_cosine_sim(a: &Tensor, b: &Tensor) -> f32 {
    let dot: f32 = a.data.iter().zip(b.data.iter()).map(|(x, y)| x * y).sum();
    let mag_a: f32 = a.data.iter().map(|v| v * v).sum::<f32>().sqrt();
    let mag_b: f32 = b.data.iter().map(|v| v * v).sum::<f32>().sqrt();
    if mag_a == 0.0 || mag_b == 0.0 { 0.0 } else { dot / (mag_a * mag_b) }
}

fn __varg_create_tensor(data: Vec<i64>) -> Tensor {
    let data_f32 = data.into_iter().map(|x| x as f32).collect::<Vec<f32>>();
    let len = data_f32.len();
    Tensor { data: data_f32, shape: vec![len] }
}

pub struct Box<T> {
    pub value: T,
}

struct BoxManager { /* Agent state */ }

impl BoxManager {
    pub fn UnwrapBox<T>(&mut self, my_box: Box<T>) {
        println!("{:?}", "Unwrapping generic box containing:".to_string());
        println!("{:?}", my_box.value);
    }
    pub fn TestCollections(&mut self) {
        let mut my_names = vec!["Varg".to_string(), "Egregore".to_string(), "AI".to_string()];
        println!("{:?}", "First name is:".to_string());
        println!("{:?}", my_names[0 as usize].clone());
        let mut my_scores = std::collections::HashMap::from([("Varg".to_string(), 100), ("Python".to_string(), 0)]);
        println!("{:?}", "Varg score:".to_string());
        println!("{:?}", my_scores.get(&"Varg".to_string()).unwrap().clone());
    }
}

