use varg_ast::ast::*;

pub struct RustGenerator;

impl RustGenerator {
    pub fn new() -> Self {
        Self {}
    }

    pub fn generate(&self, program: &Program) -> String {
        let mut output = String::new();
        output.push_str("// --- AUTOGENERATED BY Varg Compiler ---\n");
        output.push_str("use varg_os_types::*;\n");
        output.push_str("use varg_runtime::*;\n\n");

        for item in &program.items {
            output.push_str(&self.gen_item(item));
            output.push('\n');
        }

        output
    }

    fn gen_item(&self, item: &Item) -> String {
        match item {
            Item::Import(_) => String::new(), // Merged by vargc beforehand
            Item::TypeAlias { name, target } => {
                format!("type {} = {};\n", name, self.gen_type(target))
            },
            Item::Enum(e) => {
                let vis = if e.is_public { "pub " } else { "" };
                let mut out = format!("#[derive(Debug, Clone, PartialEq)]\n{}enum {} {{\n", vis, e.name);
                for variant in &e.variants {
                    if variant.fields.is_empty() {
                        out.push_str(&format!("    {},\n", variant.name));
                    } else {
                        let fields: Vec<String> = variant.fields.iter()
                            .map(|(name, ty)| format!("{}: {}", name, self.gen_type(ty)))
                            .collect();
                        out.push_str(&format!("    {} {{ {} }},\n", variant.name, fields.join(", ")));
                    }
                }
                out.push_str("}\n");
                out
            },
            Item::Struct(s) => {
                let vis = if s.is_public { "pub " } else { "" };
                let type_params = if s.type_params.is_empty() { "".to_string() } else { format!("<{}>", s.type_params.join(", ")) };
                let mut out = format!("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n{}struct {}{} {{\n", vis, s.name, type_params);
                for field in &s.fields {
                    // MVP: all generated fields are pub to the struct
                    out.push_str(&format!("    pub {}: {},\n", field.name, self.gen_type(&field.ty)));
                }
                out.push_str("}\n");
                out
            },
            Item::Contract(c) => {
                let vis = if c.is_public { "pub " } else { "" };
                let mut out = format!("{}trait {} {{\n", vis, c.name);
                for method in &c.methods {
                    out.push_str(&format!("    {};\n", self.gen_method_signature(method, true)));
                }
                out.push_str("}\n");
                out
            },
            Item::Agent(a) => {
                // An Agent translates to a struct with state, and an impl block
                let vis = if a.is_public { "pub " } else { "" };
                let mut out = format!("{}struct {} {{ /* Agent state */ }}\n\n", vis, a.name);
                out.push_str(&format!("impl {} {{\n", a.name));
                
                // Agent-level Annotations
                for ann in &a.annotations {
                    if ann.name == "CliCommand" {
                        out.push_str(&format!("    pub fn run_cli(&mut self) {{\n        println!(\"Starting CLI for agent {}...\");\n        // TODO: Map clap args to methods\n    }}\n", a.name));
                    }
                }

                for method in &a.methods {
                    // Method-level Annotations
                    for ann in &method.annotations {
                        if ann.name == "McpTool" {
                            let desc = ann.values.join(" ");
                            out.push_str(&format!("    pub fn {}_mcp_schema() -> String {{\n        r#\"{{ \"name\": \"{}\", \"description\": \"{}\" }}\"#.to_string()\n    }}\n", 
                                method.name, method.name, desc));
                        }
                    }

                    out.push_str(&format!("    {} {{\n", self.gen_method_signature(method, false)));
                    if let Some(body) = &method.body {
                        out.push_str(&self.gen_block(body, 2));
                    }
                    out.push_str("    }\n");
                }
                out.push_str("}\n");
                out
            }
        }
    }

    fn gen_method_signature(&self, method: &MethodDecl, force_no_vis: bool) -> String {
        let vis = if method.is_public && !force_no_vis { "pub " } else { "" };
        let args: Vec<String> = method.args.iter()
            .map(|a| format!("{}: {}", a.name, self.gen_type(&a.ty)))
            .collect();
        let arg_str = if args.is_empty() { "&mut self".to_string() } else { format!("&mut self, {}", args.join(", ")) };
        
        let ret_str = match &method.return_ty {
            Some(TypeNode::Void) | None => "".to_string(),
            Some(ty) => format!(" -> {}", self.gen_type(ty)),
        };

        let type_params = if method.type_params.is_empty() { "".to_string() } else { format!("<{}>", method.type_params.join(", ")) };
        let where_clause = if method.constraints.is_empty() {
            "".to_string()
        } else {
            let constraints: Vec<String> = method.constraints.iter()
                .map(|c| format!("{}: {}", c.type_param, c.bound))
                .collect();
            format!(" where {}", constraints.join(", "))
        };
        let async_kw = if method.is_async { "async " } else { "" };
        format!("{}{}fn {}{}({}){}{}", vis, async_kw, method.name, type_params, arg_str, ret_str, where_clause)
    }

    /// Heuristic: does this expression produce a String?
    fn is_string_expr(&self, expr: &Expression) -> bool {
        matches!(expr, Expression::String(_) | Expression::PromptLiteral(_))
    }

    fn gen_type(&self, ty: &TypeNode) -> String {
        match ty {
            TypeNode::Int => "i64".to_string(),
            TypeNode::Ulong => "u64".to_string(),
            TypeNode::String => "String".to_string(),
            TypeNode::Bool => "bool".to_string(),
            TypeNode::Void => "()".to_string(),
            
            // Native AI Types map directly to Rust OS types
            TypeNode::Prompt => "Prompt".to_string(),
            TypeNode::Context => "Context".to_string(),
            TypeNode::Tensor => "Tensor".to_string(),
            TypeNode::Embedding => "Embedding".to_string(),
            
            TypeNode::Nullable(inner) => format!("Option<{}>", self.gen_type(inner)),
            TypeNode::Result(ok, err) => format!("std::result::Result<{}, {}>", self.gen_type(ok), self.gen_type(err)),
            TypeNode::Error => "String".to_string(),
            TypeNode::TypeMapShort => "std::collections::HashMap<String, String>".to_string(),
            TypeNode::Array(inner) => format!("Vec<{}>", self.gen_type(inner)),
            TypeNode::List(inner) => format!("Vec<{}>", self.gen_type(inner)),
            TypeNode::Map(k, v) => format!("std::collections::HashMap<{}, {}>", self.gen_type(k), self.gen_type(v)),
            TypeNode::TypeVar(name) => name.clone(),
            TypeNode::Generic(name, args) => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.gen_type(a)).collect();
                format!("{}<{}>", name, arg_strs.join(", "))
            },
            TypeNode::Capability(cap) => {
                match cap {
                    CapabilityType::NetworkAccess => "NetworkAccess".to_string(),
                    CapabilityType::FileAccess => "FileAccess".to_string(),
                    CapabilityType::DbAccess => "DbAccess".to_string(),
                    CapabilityType::LlmAccess => "LlmAccess".to_string(),
                    CapabilityType::SystemAccess => "SystemAccess".to_string(),
                }
            },
            TypeNode::Func(params, ret) => {
                let param_strs: Vec<String> = params.iter().map(|p| self.gen_type(p)).collect();
                format!("Box<dyn Fn({}) -> {}>", param_strs.join(", "), self.gen_type(ret))
            },
            TypeNode::Custom(name) => {
                if name == "Dynamic" {
                    "String".to_string() // MVP Fallback for empty []
                } else if name == "Iterator" {
                    "Vec<String>".to_string() // MVP for LINQ eval
                } else {
                    name.clone()
                }
            },
        }
    }

    fn gen_block(&self, block: &Block, indent_level: usize) -> String {
        let indent = "    ".repeat(indent_level);
        let mut out = String::new();
        for stmt in &block.statements {
            match stmt {
                Statement::Let { name, ty: _, value } => {
                    out.push_str(&format!("{}let mut {} = {};\n", indent, name, self.gen_expression(value)));
                },
                Statement::Assign { name, value } => {
                    // Optimization: detect `name = name + expr` where string → name.push_str(...)
                    if let Expression::BinaryOp { left, operator: BinaryOperator::Add, right } = value {
                        if let Expression::Identifier(ref lhs_name) = **left {
                            if lhs_name == name && (self.is_string_expr(left) || self.is_string_expr(right)) {
                                // For string literals, use direct &str to avoid allocation
                                if let Expression::String(ref s) = **right {
                                    out.push_str(&format!("{}{}.push_str({:?});\n", indent, name, s));
                                } else {
                                    out.push_str(&format!("{}{}.push_str(&({}).to_string());\n", indent, name, self.gen_expression(right)));
                                }
                                continue;
                            }
                        }
                    }
                    out.push_str(&format!("{}{} = {};\n", indent, name, self.gen_expression(value)));
                },
                Statement::IndexAssign { target, index, value } => {
                    let idx_str = self.gen_expression(index);
                    if let Expression::String(_) = index {
                        // String literal key → map insert
                        out.push_str(&format!("{}{}.insert({}, {});\n", indent, self.gen_expression(target), idx_str, self.gen_expression(value)));
                    } else {
                        // Int literal or int variable → array index assign
                        out.push_str(&format!("{}{}[{} as usize] = {};\n", indent, self.gen_expression(target), idx_str, self.gen_expression(value)));
                    }
                },
                Statement::PropertyAssign { target, property, value } => {
                    out.push_str(&format!("{}{}.{} = {};\n", indent, self.gen_expression(target), property, self.gen_expression(value)));
                },
                Statement::Return(Some(expr)) => {
                    out.push_str(&format!("{}return {};\n", indent, self.gen_expression(expr)));
                },
                Statement::Return(None) => {
                    out.push_str(&format!("{}return;\n", indent));
                },
                Statement::UnsafeBlock(inner) => {
                    // Hardware access / DB Queries map perfectly to Rust's unsafe block paradigm
                    out.push_str(&format!("{}unsafe {{\n", indent));
                    out.push_str(&self.gen_block(inner, indent_level + 1));
                    out.push_str(&format!("{}}}\n", indent));
                },

                Statement::Const { name, ty, value } => {
                    let val_str = self.gen_expression(value);
                    if let Some(t) = ty {
                        out.push_str(&format!("{}let {}: {} = {};\n", indent, name, self.gen_type(t), val_str));
                    } else {
                        out.push_str(&format!("{}let {} = {};\n", indent, name, val_str));
                    }
                },
                Statement::Break => {
                    out.push_str(&format!("{}break;\n", indent));
                },
                Statement::Continue => {
                    out.push_str(&format!("{}continue;\n", indent));
                },
                Statement::If { condition, then_block, else_block } => {
                    out.push_str(&format!("{}if {} {{\n", indent, self.gen_expression(condition)));
                    out.push_str(&self.gen_block(then_block, indent_level + 1));
                    if let Some(eb) = else_block {
                        // Detect else-if chain: single If statement in else block
                        if eb.statements.len() == 1 {
                            if let Statement::If { condition: elif_cond, then_block: elif_then, else_block: elif_else } = &eb.statements[0] {
                                out.push_str(&format!("{}}} else if {} {{\n", indent, self.gen_expression(elif_cond)));
                                out.push_str(&self.gen_block(elif_then, indent_level + 1));
                                if let Some(final_else) = elif_else {
                                    // Check for further chaining
                                    if final_else.statements.len() == 1 {
                                        if let Statement::If { .. } = &final_else.statements[0] {
                                            // Recurse: generate the rest of the chain via gen_block
                                            // which will hit this same branch
                                            let chain = self.gen_block(final_else, indent_level);
                                            // Strip the leading indent from the generated if
                                            let trimmed = chain.trim_start();
                                            out.push_str(&format!("{}}} else {}", indent, trimmed));
                                            continue;
                                        }
                                    }
                                    out.push_str(&format!("{}}} else {{\n", indent));
                                    out.push_str(&self.gen_block(final_else, indent_level + 1));
                                }
                                out.push_str(&format!("{}}}\n", indent));
                                continue;
                            }
                        }
                        out.push_str(&format!("{}}} else {{\n", indent));
                        out.push_str(&self.gen_block(eb, indent_level + 1));
                    }
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::While { condition, body } => {
                    out.push_str(&format!("{}while {} {{\n", indent, self.gen_expression(condition)));
                    out.push_str(&self.gen_block(body, indent_level + 1));
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::For { init, condition, update, body } => {
                    out.push_str(&format!("{}{{\n", indent));
                    out.push_str(&self.gen_block(&Block { statements: vec![*init.clone()] }, indent_level + 1));
                    out.push_str(&format!("{}    while {} {{\n", indent, self.gen_expression(condition)));
                    out.push_str(&self.gen_block(body, indent_level + 2));
                    out.push_str(&self.gen_block(&Block { statements: vec![*update.clone()] }, indent_level + 2));
                    out.push_str(&format!("{}    }}\n", indent));
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::Foreach { item_name, collection, body } => {
                    out.push_str(&format!("{}for mut {} in {} {{\n", indent, item_name, self.gen_expression(collection)));
                    out.push_str(&self.gen_block(body, indent_level + 1));
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::Stream(expr) => {
                    if let Expression::MethodCall { method_name, args, .. } = expr {
                        if method_name == "llm_chat" {
                            let ctx = if args.len() > 0 { format!("&mut {}", self.gen_expression(&args[0])) } else { "\"\"".to_string() };
                            let prompt = if args.len() > 1 { self.gen_expression(&args[1]) } else { "\"\"".to_string() };
                            let model = if args.len() > 2 { self.gen_expression(&args[2]) } else { "\"llama3\"".to_string() };
                            out.push_str(&format!("{}__varg_llm_chat_stream({}, &{}, &{});\n", indent, ctx, prompt, model));
                        } else if method_name == "llm_infer" {
                            let prompt = if args.len() > 0 { self.gen_expression(&args[0]) } else { "\"\"".to_string() };
                            let model = if args.len() > 1 { self.gen_expression(&args[1]) } else { "\"llama3\"".to_string() };
                            out.push_str(&format!("{}__varg_llm_infer_stream(&{}, &{});\n", indent, prompt, model));
                        } else {
                            out.push_str(&format!("{}print!(\"{{}}\", {});\n{}use std::io::Write; std::io::stdout().flush().unwrap();\n", indent, self.gen_expression(expr), indent));
                        }
                    } else {
                        out.push_str(&format!("{}print!(\"{{}}\", {});\n{}use std::io::Write; std::io::stdout().flush().unwrap();\n", indent, self.gen_expression(expr), indent));
                    }
                },
                Statement::Print(expr) => {
                    // Use Display ({}) for strings, Debug ({:?}) for other types
                    if self.is_string_expr(expr) {
                        out.push_str(&format!("{}println!(\"{{}}\", {});\n", indent, self.gen_expression(expr)));
                    } else if let Expression::Identifier(_) = expr {
                        // Identifiers could be any type — use Debug for safety
                        out.push_str(&format!("{}println!(\"{{:?}}\", {});\n", indent, self.gen_expression(expr)));
                    } else {
                        out.push_str(&format!("{}println!(\"{{:?}}\", {});\n", indent, self.gen_expression(expr)));
                    }
                },
                Statement::Expr(expr) => {
                    out.push_str(&format!("{}{};\n", indent, self.gen_expression(expr)));
                },
                Statement::TryCatch { try_block, catch_var, catch_block } => {
                    out.push_str(&format!("{}#[allow(unreachable_code, unused_labels)]\n", indent));
                    out.push_str(&format!("{}let _varg_try_res: std::result::Result<(), String> = 'varg_try: {{\n", indent));
                    out.push_str(&self.gen_block(try_block, indent_level + 1));
                    out.push_str(&format!("{}    Ok(())\n", indent));
                    out.push_str(&format!("{}}};\n", indent));
                    out.push_str(&format!("{}if let Err(mut {}) = _varg_try_res {{\n", indent, catch_var));
                    out.push_str(&self.gen_block(catch_block, indent_level + 1));
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::Throw(expr) => {
                    out.push_str(&format!("{}break 'varg_try Err(format!(\"{{}}\", {}));\n", indent, self.gen_expression(expr)));
                },
                Statement::LetDestructure { pattern, value } => {
                    let val_str = self.gen_expression(value);
                    match pattern {
                        DestructurePattern::Tuple(names) => {
                            out.push_str(&format!("{}let ({}) = {};\n", indent, names.join(", "), val_str));
                        }
                        DestructurePattern::Struct(fields) => {
                            let field_strs: Vec<String> = fields.iter().map(|(name, alias)| {
                                match alias {
                                    Some(a) => format!("{}: {}", name, a),
                                    None => name.clone(),
                                }
                            }).collect();
                            out.push_str(&format!("{}let {{ {} }} = {};\n", indent, field_strs.join(", "), val_str));
                        }
                    }
                },
                Statement::Match { subject, arms } => {
                    out.push_str(&format!("{}match {} {{\n", indent, self.gen_expression(subject)));
                    for arm in arms {
                        let pattern_str = self.gen_pattern(&arm.pattern);
                        out.push_str(&format!("{}    {} => {{\n", indent, pattern_str));
                        out.push_str(&self.gen_block(&arm.body, indent_level + 2));
                        out.push_str(&format!("{}    }},\n", indent));
                    }
                    out.push_str(&format!("{}}}\n", indent));
                },
            }
        }
        out
    }

    fn gen_pattern(&self, pattern: &Pattern) -> String {
        match pattern {
            Pattern::Wildcard => "_".to_string(),
            Pattern::Literal(expr) => self.gen_expression(expr),
            Pattern::Variant(name, bindings) => {
                if bindings.is_empty() {
                    name.clone()
                } else {
                    format!("{}({})", name, bindings.join(", "))
                }
            },
        }
    }

    fn gen_expression(&self, expr: &Expression) -> String {
        match expr {
            Expression::Null => "None".to_string(),
            Expression::Int(i) => i.to_string(),
            Expression::String(s) => format!("{:?}.to_string()", s),
            Expression::PromptLiteral(s) => {
                let mut stripped = String::new();
                let mut args = Vec::new();
                let mut chars = s.chars().peekable();
                while let Some(c) = chars.next() {
                    if c == '$' && chars.peek() == Some(&'{') {
                        chars.next(); // consume '{'
                        let mut expr_str = String::new();
                        while let Some(inner_c) = chars.next() {
                            if inner_c == '}' { break; }
                            expr_str.push(inner_c);
                        }
                        stripped.push_str("{}");
                        args.push(expr_str); 
                    } else if c == '{' {
                        stripped.push_str("{{");
                    } else if c == '}' {
                        stripped.push_str("}}");
                    } else {
                        stripped.push(c);
                    }
                }
                
                let args_joined = if args.is_empty() {
                    "".to_string()
                } else {
                    format!(", {}", args.join(", "))
                };
                
                format!("Prompt {{ text: format!({:?}{}) }}", stripped, args_joined)
            },
            Expression::Bool(b) => b.to_string(),
            Expression::Identifier(name) => name.clone(),
            Expression::BinaryOp { left, operator, right } => {
                if let BinaryOperator::CosineSim = operator {
                    return format!("__varg_cosine_sim(&{}, &{})", self.gen_expression(left), self.gen_expression(right));
                }

                // String concatenation: format! for expression-level concat
                if let BinaryOperator::Add = operator {
                    if self.is_string_expr(left) || self.is_string_expr(right) {
                        return format!("format!(\"{{}}{{}}\", {}, {})", self.gen_expression(left), self.gen_expression(right));
                    }
                }

                let op = match operator {
                    BinaryOperator::Add => "+",
                    BinaryOperator::Sub => "-",
                    BinaryOperator::Mul => "*",
                    BinaryOperator::Div => "/",
                    BinaryOperator::Mod => "%",
                    BinaryOperator::Eq => "==",
                    BinaryOperator::NotEq => "!=",
                    BinaryOperator::Lt => "<",
                    BinaryOperator::Gt => ">",
                    BinaryOperator::LtEq => "<=",
                    BinaryOperator::GtEq => ">=",
                    BinaryOperator::And => "&&",
                    BinaryOperator::Or => "||",
                    BinaryOperator::CosineSim => unreachable!(),
                };
                format!("{} {} {}", self.gen_expression(left), op, self.gen_expression(right))
            },
            Expression::Await(inner) => {
                format!("{}.await", self.gen_expression(inner))
            },
            Expression::UnaryOp { operator, operand } => {
                let expr = self.gen_expression(operand);
                match operator {
                    UnaryOperator::Negate => format!("-{}", expr),
                    UnaryOperator::Not => format!("!{}", expr),
                }
            },
            Expression::MethodCall { caller, method_name, args } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.gen_expression(a)).collect();
                if method_name == "encrypt" {
                    format!("__varg_encrypt(&{}, &{})", arg_strs[0], arg_strs[1])
                } else if method_name == "decrypt" {
                    format!("__varg_decrypt(&{}, &{})", arg_strs[0], arg_strs[1])
                } else if method_name == "fetch" {
                    let url = if arg_strs.len() > 0 { &arg_strs[0] } else { "\"\"" };
                    let met = if arg_strs.len() > 1 { &arg_strs[1] } else { "\"GET\"" };
                    let hdr = if arg_strs.len() > 2 { &arg_strs[2] } else { "std::collections::HashMap::new()" };
                    let bod = if arg_strs.len() > 3 { &arg_strs[3] } else { "\"\"" };
                    format!("__varg_fetch(&{}, &{}, {}, &{})", url, met, hdr, bod)
                } else if method_name == "llm_infer" {
                    let prompt = if arg_strs.len() > 0 { &arg_strs[0] } else { "\"\"" };
                    let model = if arg_strs.len() > 1 { &arg_strs[1] } else { "\"llama3\"" };
                    format!("__varg_llm_infer(&{}, &{})", prompt, model)
                } else if method_name == "llm_chat" {
                    let ctx = if arg_strs.len() > 0 { format!("&mut {}", arg_strs[0]) } else { "\"\"".to_string() };
                    let prompt = if arg_strs.len() > 1 { &arg_strs[1] } else { "\"\"" };
                    let model = if arg_strs.len() > 2 { &arg_strs[2] } else { "\"llama3\"" };
                    format!("__varg_llm_chat({}, &{}, &{})", ctx, prompt, model)
                } else if method_name == "to_json" {
                    format!("serde_json::to_string(&{}).unwrap_or_else(|e| format!(\"{{}}\", e))", arg_strs[0])
                } else if method_name == "from_json" {
                    // For MVP: parse into a flat String HashMap
                    format!("serde_json::from_str::<std::collections::HashMap<String, String>>(&{}).unwrap_or_default()", arg_strs[0])
                } else if method_name == "__varg_create_tensor" {
                    format!("__varg_create_tensor({})", arg_strs[0])
                } else if method_name == "__varg_create_context" {
                    format!("__varg_create_context(&{})", arg_strs[0])
                } else if method_name == "context_from" {
                    format!("__varg_context_from(&{})", arg_strs[0])
                } else if method_name == "file_read" {
                    format!("std::fs::read_to_string(&{}).unwrap_or_else(|e| format!(\"{{}}\", e))", arg_strs[0])
                } else if method_name == "file_write" {
                    format!("std::fs::write(&{}, &{}).unwrap()", arg_strs[0], arg_strs[1])
                } else if method_name == "time_now" {
                    "(std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_secs() as i64)".to_string()
                } else if method_name == "str_replace" {
                    format!("{}.replace(&{}, &{})", arg_strs[0], arg_strs[1], arg_strs[2])
                } else if method_name == "str_trim" {
                    format!("{}.trim().to_string()", arg_strs[0])
                } else if method_name == "str_split" {
                    format!("{}.split(&{}).map(|s| s.to_string()).collect::<Vec<String>>()", arg_strs[0], arg_strs[1])
                // ===== Wave 5: String Methods (caller-as-receiver) =====
                } else if method_name == "len" {
                    format!("{}.len() as i64", self.gen_expression(caller))
                } else if method_name == "contains" {
                    format!("{}.contains(&{})", self.gen_expression(caller), arg_strs[0])
                } else if method_name == "starts_with" {
                    format!("{}.starts_with(&{})", self.gen_expression(caller), arg_strs[0])
                } else if method_name == "ends_with" {
                    format!("{}.ends_with(&{})", self.gen_expression(caller), arg_strs[0])
                } else if method_name == "to_upper" {
                    format!("{}.to_uppercase()", self.gen_expression(caller))
                } else if method_name == "to_lower" {
                    format!("{}.to_lowercase()", self.gen_expression(caller))
                } else if method_name == "substring" {
                    format!("{}.chars().skip({} as usize).take({} as usize).collect::<String>()", self.gen_expression(caller), arg_strs[0], arg_strs[1])
                } else if method_name == "char_at" {
                    format!("{}.chars().nth({} as usize).map(|c| c.to_string()).unwrap_or_default()", self.gen_expression(caller), arg_strs[0])
                } else if method_name == "index_of" {
                    format!("{}.find(&{}).map(|i| i as i64).unwrap_or(-1)", self.gen_expression(caller), arg_strs[0])
                } else if method_name == "trim" {
                    format!("{}.trim().to_string()", self.gen_expression(caller))
                } else if method_name == "split" {
                    format!("{}.split(&{}).map(|s| s.to_string()).collect::<Vec<String>>()", self.gen_expression(caller), arg_strs[0])
                } else if method_name == "replace" {
                    format!("{}.replace(&{}, &{})", self.gen_expression(caller), arg_strs[0], arg_strs[1])
                // ===== Wave 5: Collection Methods =====
                } else if method_name == "push" {
                    format!("{}.push({})", self.gen_expression(caller), arg_strs[0])
                } else if method_name == "pop" {
                    format!("{}.pop().unwrap()", self.gen_expression(caller))
                } else if method_name == "reverse" {
                    format!("{}.reverse()", self.gen_expression(caller))
                } else if method_name == "is_empty" {
                    format!("{}.is_empty()", self.gen_expression(caller))
                } else if method_name == "keys" {
                    format!("{}.keys().cloned().collect::<Vec<_>>()", self.gen_expression(caller))
                } else if method_name == "values" {
                    format!("{}.values().cloned().collect::<Vec<_>>()", self.gen_expression(caller))
                } else if method_name == "contains_key" {
                    format!("{}.contains_key(&{})", self.gen_expression(caller), arg_strs[0])
                } else if method_name == "remove" {
                    format!("{}.remove(&{})", self.gen_expression(caller), arg_strs[0])
                } else {
                    format!("{}.{}({})", self.gen_expression(caller), method_name, arg_strs.join(", "))
                }
            },
            Expression::PropertyAccess { caller, property_name } => {
                format!("{}.{}", self.gen_expression(caller), property_name)
            },
            Expression::IndexAccess { caller, index } => {
                let idx_str = self.gen_expression(index);
                if let Expression::String(_) = **index {
                    // String literal key → map access
                    format!("{}.get(&{}).unwrap().clone()", self.gen_expression(caller), idx_str)
                } else {
                    // Int literal or int variable → array access (no .clone() needed for Copy types)
                    format!("{}[{} as usize]", self.gen_expression(caller), idx_str)
                }
            },
            Expression::ArrayLiteral(elements) => {
                let elems: Vec<String> = elements.iter().map(|e| self.gen_expression(e)).collect();
                format!("vec![{}]", elems.join(", "))
            },
            Expression::MapLiteral(entries) => {
                let pairs: Vec<String> = entries.iter().map(|(k, v)| format!("({}, {})", self.gen_expression(k), self.gen_expression(v))).collect();
                format!("std::collections::HashMap::from([{}])", pairs.join(", "))
            },
            Expression::Linq(q) => {
                // LINQ transpiles into a highly efficient Rust Iterator chain
                let mut rust_query = format!("{}.clone().into_iter()", self.gen_expression(&q.in_collection));
                
                if let Some(where_c) = &q.where_clause {
                    rust_query.push_str(&format!(".filter(|{}| {})", q.from_var, self.gen_expression(where_c)));
                }

                if let Some(orderby_c) = &q.orderby_clause {
                    rust_query = format!("{{ let mut _ltmp = {}.collect::<Vec<_>>(); _ltmp.sort_by_key(|{}| {}); if {} {{ _ltmp.reverse(); }} _ltmp.into_iter() }}", 
                        rust_query, q.from_var, self.gen_expression(orderby_c), q.descending);
                }

                rust_query.push_str(&format!(".map(|{}| {}).collect::<Vec<_>>()", q.from_var, self.gen_expression(&q.select_clause)));
                
                rust_query
            },
            Expression::Lambda { params, return_ty: _, body } => {
                let param_strs: Vec<String> = params.iter()
                    .map(|p| format!("{}: {}", p.name, self.gen_type(&p.ty)))
                    .collect();
                let body_str = match body.as_ref() {
                    LambdaBody::Expression(expr) => self.gen_expression(expr),
                    LambdaBody::Block(block) => {
                        format!("{{\n{}}}", self.gen_block(block, 1))
                    },
                };
                format!("|{}| {}", param_strs.join(", "), body_str)
            },
            Expression::Query(q) => {
                // Native embedded DB call
                format!("__varg_query({:?})", q.raw_query)
            },
            // Wave 6: retry(N) { body } fallback { fallback_body }
            Expression::Retry { max_attempts, body, fallback } => {
                let attempts_str = self.gen_expression(max_attempts);
                let body_str = self.gen_block(body, 2);
                let fallback_str = if let Some(fb) = fallback {
                    format!("{{ {} }}", self.gen_block(fb, 3).trim())
                } else {
                    "{ panic!(\"retry: all attempts failed\") }".to_string()
                };
                format!("{{\n    let mut __retry_result = None;\n    for __retry_i in 0..{} {{\n        match (|| -> std::result::Result<_, String> {{\n            Ok({{\n{}\n            }})\n        }})() {{\n            Ok(val) => {{ __retry_result = Some(val); break; }}\n            Err(_) => {{}}\n        }}\n    }}\n    __retry_result.unwrap_or_else(|| {})\n}}", attempts_str, body_str.trim(), fallback_str)
            },
            // Wave 6: spawn Agent(args)
            Expression::Spawn { agent_name, args } => {
                let args_str: Vec<String> = args.iter().map(|a| self.gen_expression(a)).collect();
                if args_str.is_empty() {
                    format!("{{\n    let (tx, rx) = std::sync::mpsc::channel();\n    std::thread::spawn(move || {{\n        let mut __agent = {} {{}};\n        for (method, args, reply_tx) in rx {{\n            let result = \"ok\".to_string();\n            if let Some(reply) = reply_tx {{ let _ = reply.send(result); }}\n        }}\n    }});\n    tx\n}}", agent_name)
                } else {
                    format!("{{\n    let (tx, rx) = std::sync::mpsc::channel();\n    std::thread::spawn(move || {{\n        let mut __agent = {} {{}};\n        for (method, args, reply_tx) in rx {{\n            let result = \"ok\".to_string();\n            if let Some(reply) = reply_tx {{ let _ = reply.send(result); }}\n        }}\n    }});\n    tx\n}}", agent_name)
                }
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_codegen_agent() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "MemoryAgent".to_string(),
                is_system: false,
                is_public: true,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Recall".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::String),
                    body: Some(Block {
                        statements: vec![
                            Statement::Let {
                                name: "mem".to_string(),
                                ty: Some(TypeNode::String),
                                value: Expression::String("Data".to_string()),
                            },
                            Statement::Return(Some(Expression::Identifier("mem".to_string()))),
                        ]
                    })
                }]
            })]
        };

        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        
        assert!(code.contains("pub struct MemoryAgent"));
        assert!(code.contains("pub fn Recall(&mut self) -> String"));
        assert!(code.contains("let mut mem = \"Data\".to_string();"));
        assert!(code.contains("return mem;"));
    }

    // ---- Plan 08: Extended CodeGen Coverage ----

    #[test]
    fn test_codegen_contract_trait() {
        let program = Program {
            no_std: false,
            items: vec![Item::Contract(ContractDef {
                name: "Searchable".to_string(),
                is_public: true,
                target_annotation: None,
                methods: vec![
                    MethodDecl {
                        name: "Find".to_string(),
                        is_public: true, is_async: false,
                        annotations: vec![],
                        type_params: vec![],
                        constraints: vec![],
                        args: vec![FieldDecl { name: "query".to_string(), ty: TypeNode::String }],
                        return_ty: Some(TypeNode::String),
                        body: None,
                    },
                ],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("pub trait Searchable"));
        assert!(code.contains("fn Find(&mut self, query: String) -> String;"));
    }

    #[test]
    fn test_codegen_struct() {
        let program = Program {
            no_std: false,
            items: vec![Item::Struct(StructDef {
                name: "UserProfile".to_string(),
                is_public: true,
                type_params: vec![],
                fields: vec![
                    FieldDecl { name: "name".to_string(), ty: TypeNode::String },
                    FieldDecl { name: "age".to_string(), ty: TypeNode::Int },
                    FieldDecl { name: "active".to_string(), ty: TypeNode::Bool },
                ],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("pub struct UserProfile"));
        assert!(code.contains("pub name: String,"));
        assert!(code.contains("pub age: i64,"));
        assert!(code.contains("pub active: bool,"));
        // Plan 18: Structs get serde derives for JSON serialization
        assert!(code.contains("serde::Serialize"));
        assert!(code.contains("serde::Deserialize"));
    }

    #[test]
    fn test_codegen_if_else() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::If {
                                condition: Expression::Bool(true),
                                then_block: Block {
                                    statements: vec![Statement::Print(Expression::String("yes".to_string()))]
                                },
                                else_block: Some(Block {
                                    statements: vec![Statement::Print(Expression::String("no".to_string()))]
                                }),
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("if true {"));
        assert!(code.contains("} else {"));
    }

    #[test]
    fn test_codegen_while_loop() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::While {
                                condition: Expression::Bool(true),
                                body: Block {
                                    statements: vec![Statement::Return(None)]
                                },
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("while true {"));
        assert!(code.contains("return;"));
    }

    #[test]
    fn test_codegen_foreach() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Foreach {
                                item_name: "item".to_string(),
                                collection: Expression::Identifier("items".to_string()),
                                body: Block {
                                    statements: vec![Statement::Print(Expression::Identifier("item".to_string()))]
                                },
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("for mut item in items {"));
    }

    #[test]
    fn test_codegen_try_catch() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::TryCatch {
                                try_block: Block {
                                    statements: vec![Statement::Throw(Expression::String("error".to_string()))]
                                },
                                catch_var: "err".to_string(),
                                catch_block: Block {
                                    statements: vec![Statement::Print(Expression::Identifier("err".to_string()))]
                                },
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("'varg_try:"));
        assert!(code.contains("if let Err(mut err)"));
        assert!(code.contains("break 'varg_try Err("));
    }

    #[test]
    fn test_codegen_print() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Print(Expression::String("hello world".to_string()))
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("println!(\"{:?}\","));
    }

    #[test]
    fn test_codegen_binary_ops() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Let {
                                name: "sum".to_string(),
                                ty: None,
                                value: Expression::BinaryOp {
                                    left: Box::new(Expression::Int(1)),
                                    operator: BinaryOperator::Add,
                                    right: Box::new(Expression::Int(2)),
                                },
                            },
                            Statement::Let {
                                name: "eq".to_string(),
                                ty: None,
                                value: Expression::BinaryOp {
                                    left: Box::new(Expression::Int(1)),
                                    operator: BinaryOperator::Eq,
                                    right: Box::new(Expression::Int(1)),
                                },
                            },
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("1 + 2"));
        assert!(code.contains("1 == 1"));
    }

    #[test]
    fn test_codegen_array_literal() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Let {
                                name: "arr".to_string(),
                                ty: None,
                                value: Expression::ArrayLiteral(vec![
                                    Expression::Int(1),
                                    Expression::Int(2),
                                    Expression::Int(3),
                                ]),
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("vec![1, 2, 3]"));
    }

    #[test]
    fn test_codegen_unsafe_block() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: true,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::UnsafeBlock(Block {
                                statements: vec![Statement::Return(None)]
                            })
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("unsafe {"));
        assert!(code.contains("return;"));
    }

    #[test]
    fn test_codegen_method_with_where_clause() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Sort".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec!["T".to_string()],
                    constraints: vec![GenericConstraint {
                        type_param: "T".to_string(),
                        bound: "Comparable".to_string(),
                    }],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![] })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("fn Sort<T>"));
        assert!(code.contains("where T: Comparable"));
    }

    #[test]
    fn test_codegen_all_type_mappings() {
        // Test that all Varg types map to correct Rust types
        let gen = RustGenerator::new();
        assert_eq!(gen.gen_type(&TypeNode::Int), "i64");
        assert_eq!(gen.gen_type(&TypeNode::Ulong), "u64");
        assert_eq!(gen.gen_type(&TypeNode::String), "String");
        assert_eq!(gen.gen_type(&TypeNode::Bool), "bool");
        assert_eq!(gen.gen_type(&TypeNode::Void), "()");
        assert_eq!(gen.gen_type(&TypeNode::Prompt), "Prompt");
        assert_eq!(gen.gen_type(&TypeNode::Context), "Context");
        assert_eq!(gen.gen_type(&TypeNode::Tensor), "Tensor");
        assert_eq!(gen.gen_type(&TypeNode::Embedding), "Embedding");
        assert_eq!(gen.gen_type(&TypeNode::Error), "String");
        assert_eq!(gen.gen_type(&TypeNode::Array(Box::new(TypeNode::Int))), "Vec<i64>");
        assert_eq!(gen.gen_type(&TypeNode::List(Box::new(TypeNode::String))), "Vec<String>");
        assert_eq!(gen.gen_type(&TypeNode::Nullable(Box::new(TypeNode::Bool))), "Option<bool>");
        assert_eq!(gen.gen_type(&TypeNode::Map(Box::new(TypeNode::String), Box::new(TypeNode::Int))), "std::collections::HashMap<String, i64>");
        assert_eq!(gen.gen_type(&TypeNode::Result(Box::new(TypeNode::String), Box::new(TypeNode::Error))), "std::result::Result<String, String>");
        assert_eq!(gen.gen_type(&TypeNode::TypeVar("T".to_string())), "T");
    }

    #[test]
    fn test_codegen_struct_with_generics() {
        let program = Program {
            no_std: false,
            items: vec![Item::Struct(StructDef {
                name: "Container".to_string(),
                is_public: true,
                type_params: vec!["T".to_string()],
                fields: vec![
                    FieldDecl { name: "value".to_string(), ty: TypeNode::TypeVar("T".to_string()) },
                ],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("pub struct Container<T>"));
        assert!(code.contains("pub value: T,"));
    }

    // ---- Plan 07 Tests ----

    #[test]
    fn test_codegen_enum() {
        let program = Program {
            no_std: false,
            items: vec![Item::Enum(EnumDef {
                name: "Status".to_string(),
                is_public: true,
                variants: vec![
                    EnumVariant { name: "Active".to_string(), fields: vec![] },
                    EnumVariant { name: "Suspended".to_string(), fields: vec![
                        ("reason".to_string(), TypeNode::String),
                    ]},
                ],
            })]
        };

        let gen = RustGenerator::new();
        let code = gen.generate(&program);

        assert!(code.contains("pub enum Status"));
        assert!(code.contains("Active,"));
        assert!(code.contains("Suspended { reason: String }"));
    }

    #[test]
    fn test_codegen_type_alias() {
        let program = Program {
            no_std: false,
            items: vec![Item::TypeAlias {
                name: "UserId".to_string(),
                target: TypeNode::String,
            }]
        };

        let gen = RustGenerator::new();
        let code = gen.generate(&program);

        assert!(code.contains("type UserId = String;"));
    }

    #[test]
    fn test_codegen_nullable_type() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![FieldDecl {
                        name: "name".to_string(),
                        ty: TypeNode::Nullable(Box::new(TypeNode::String)),
                    }],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![
                        Statement::Let {
                            name: "x".to_string(),
                            ty: None,
                            value: Expression::Null,
                        }
                    ]})
                }]
            })]
        };

        let gen = RustGenerator::new();
        let code = gen.generate(&program);

        assert!(code.contains("name: Option<String>"));
        assert!(code.contains("let mut x = None;"));
    }

    // ---- Plan 03: OCAP Capability Codegen Tests ----

    #[test]
    fn test_codegen_capability_type_mapping() {
        let gen = RustGenerator::new();
        assert_eq!(gen.gen_type(&TypeNode::Capability(CapabilityType::NetworkAccess)), "NetworkAccess");
        assert_eq!(gen.gen_type(&TypeNode::Capability(CapabilityType::FileAccess)), "FileAccess");
        assert_eq!(gen.gen_type(&TypeNode::Capability(CapabilityType::DbAccess)), "DbAccess");
        assert_eq!(gen.gen_type(&TypeNode::Capability(CapabilityType::LlmAccess)), "LlmAccess");
        assert_eq!(gen.gen_type(&TypeNode::Capability(CapabilityType::SystemAccess)), "SystemAccess");
    }

    #[test]
    fn test_codegen_method_with_capability_param() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "ApiAgent".to_string(),
                is_system: false,
                is_public: true,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Fetch".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![
                        FieldDecl { name: "url".to_string(), ty: TypeNode::String },
                        FieldDecl { name: "net".to_string(), ty: TypeNode::Capability(CapabilityType::NetworkAccess) },
                    ],
                    return_ty: Some(TypeNode::String),
                    body: Some(Block { statements: vec![
                        Statement::Return(Some(Expression::String("ok".to_string())))
                    ]})
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("url: String, net: NetworkAccess"));
    }

    // ---- Plan 06: Match Codegen Tests ----

    #[test]
    fn test_codegen_match_statement() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Let { name: "x".to_string(), ty: None, value: Expression::Int(1) },
                            Statement::Match {
                                subject: Expression::Identifier("x".to_string()),
                                arms: vec![
                                    MatchArm {
                                        pattern: Pattern::Literal(Expression::Int(1)),
                                        body: Block { statements: vec![Statement::Print(Expression::String("one".to_string()))] },
                                    },
                                    MatchArm {
                                        pattern: Pattern::Literal(Expression::Int(2)),
                                        body: Block { statements: vec![Statement::Print(Expression::String("two".to_string()))] },
                                    },
                                    MatchArm {
                                        pattern: Pattern::Wildcard,
                                        body: Block { statements: vec![Statement::Print(Expression::String("other".to_string()))] },
                                    },
                                ],
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("match x {"));
        assert!(code.contains("1 => {"));
        assert!(code.contains("2 => {"));
        assert!(code.contains("_ => {"));
    }

    #[test]
    fn test_codegen_match_variant_pattern() {
        let gen = RustGenerator::new();
        assert_eq!(gen.gen_pattern(&Pattern::Wildcard), "_");
        assert_eq!(gen.gen_pattern(&Pattern::Literal(Expression::Int(42))), "42");
        assert_eq!(gen.gen_pattern(&Pattern::Variant("None".to_string(), vec![])), "None");
        assert_eq!(gen.gen_pattern(&Pattern::Variant("Some".to_string(), vec!["val".to_string()])), "Some(val)");
    }

    // ---- Plan 06: Lambda Codegen Tests ----

    #[test]
    fn test_codegen_lambda_expression() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true, is_async: false,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Let {
                                name: "double".to_string(),
                                ty: None,
                                value: Expression::Lambda {
                                    params: vec![FieldDecl { name: "x".to_string(), ty: TypeNode::Int }],
                                    return_ty: Some(Box::new(TypeNode::Int)),
                                    body: Box::new(LambdaBody::Expression(
                                        Expression::BinaryOp {
                                            left: Box::new(Expression::Identifier("x".to_string())),
                                            operator: BinaryOperator::Mul,
                                            right: Box::new(Expression::Int(2)),
                                        }
                                    )),
                                },
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("|x: i64| x * 2"));
    }

    #[test]
    fn test_codegen_func_type_mapping() {
        let gen = RustGenerator::new();
        let func_ty = TypeNode::Func(vec![TypeNode::Int, TypeNode::String], Box::new(TypeNode::Bool));
        assert_eq!(gen.gen_type(&func_ty), "Box<dyn Fn(i64, String) -> bool>");
    }

    // ===== Plan 06: Destructuring CodeGen =====

    #[test]
    fn test_codegen_tuple_destructuring() {
        let program = Program {
            no_std: true,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false, is_public: false,
                target_annotation: None, annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(), is_public: true, is_async: false,
                    annotations: vec![], type_params: vec![], constraints: vec![],
                    args: vec![], return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![
                        Statement::LetDestructure {
                            pattern: DestructurePattern::Tuple(vec!["x".to_string(), "y".to_string()]),
                            value: Expression::Identifier("pair".to_string()),
                        },
                    ]}),
                }],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("let (x, y) = pair;"));
    }

    #[test]
    fn test_codegen_struct_destructuring() {
        let program = Program {
            no_std: true,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false, is_public: false,
                target_annotation: None, annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(), is_public: true, is_async: false,
                    annotations: vec![], type_params: vec![], constraints: vec![],
                    args: vec![], return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![
                        Statement::LetDestructure {
                            pattern: DestructurePattern::Struct(vec![
                                ("name".to_string(), None),
                                ("age".to_string(), Some("a".to_string())),
                            ]),
                            value: Expression::Identifier("person".to_string()),
                        },
                    ]}),
                }],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("let { name, age: a } = person;"));
    }

    // ===== Stabilization: Missing CodeGen Tests =====

    #[test]
    fn test_codegen_for_loop() {
        let program = Program {
            no_std: true,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false, is_public: false,
                target_annotation: None, annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(), is_public: true, is_async: false,
                    annotations: vec![], type_params: vec![], constraints: vec![],
                    args: vec![], return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![
                        Statement::For {
                            init: Box::new(Statement::Let { name: "i".to_string(), ty: None, value: Expression::Int(0) }),
                            condition: Expression::BinaryOp {
                                left: Box::new(Expression::Identifier("i".to_string())),
                                operator: BinaryOperator::Lt,
                                right: Box::new(Expression::Int(10)),
                            },
                            update: Box::new(Statement::Assign {
                                name: "i".to_string(),
                                value: Expression::BinaryOp {
                                    left: Box::new(Expression::Identifier("i".to_string())),
                                    operator: BinaryOperator::Add,
                                    right: Box::new(Expression::Int(1)),
                                },
                            }),
                            body: Block { statements: vec![
                                Statement::Print(Expression::Identifier("i".to_string())),
                            ] },
                        }
                    ]}),
                }],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("let mut i = 0;"));
        assert!(code.contains("while i < 10 {"));
        assert!(code.contains("i = i + 1;"));
    }

    #[test]
    fn test_codegen_property_access() {
        let gen = RustGenerator::new();
        let expr = Expression::PropertyAccess {
            caller: Box::new(Expression::Identifier("obj".to_string())),
            property_name: "name".to_string(),
        };
        assert_eq!(gen.gen_expression(&expr), "obj.name");
    }

    #[test]
    fn test_codegen_index_access_int() {
        let gen = RustGenerator::new();
        let expr = Expression::IndexAccess {
            caller: Box::new(Expression::Identifier("arr".to_string())),
            index: Box::new(Expression::Int(0)),
        };
        assert_eq!(gen.gen_expression(&expr), "arr[0 as usize].clone()");
    }

    #[test]
    fn test_codegen_index_access_string() {
        let gen = RustGenerator::new();
        let expr = Expression::IndexAccess {
            caller: Box::new(Expression::Identifier("map".to_string())),
            index: Box::new(Expression::Identifier("key".to_string())),
        };
        assert_eq!(gen.gen_expression(&expr), "map.get(&key).unwrap().clone()");
    }

    #[test]
    fn test_codegen_map_literal() {
        let gen = RustGenerator::new();
        let expr = Expression::MapLiteral(vec![
            (Expression::String("a".to_string()), Expression::Int(1)),
            (Expression::String("b".to_string()), Expression::Int(2)),
        ]);
        let code = gen.gen_expression(&expr);
        assert!(code.contains("HashMap::from("));
        assert!(code.contains("(\"a\".to_string(), 1)"));
        assert!(code.contains("(\"b\".to_string(), 2)"));
    }

    #[test]
    fn test_codegen_linq_query() {
        let gen = RustGenerator::new();
        let expr = Expression::Linq(LinqQuery {
            from_var: "x".to_string(),
            in_collection: Box::new(Expression::Identifier("items".to_string())),
            where_clause: Some(Box::new(Expression::BinaryOp {
                left: Box::new(Expression::Identifier("x".to_string())),
                operator: BinaryOperator::Gt,
                right: Box::new(Expression::Int(5)),
            })),
            orderby_clause: None,
            descending: false,
            select_clause: Box::new(Expression::Identifier("x".to_string())),
        });
        let code = gen.gen_expression(&expr);
        assert!(code.contains("items.clone().into_iter()"));
        assert!(code.contains(".filter(|x| x > 5)"));
        assert!(code.contains(".map(|x| x).collect::<Vec<_>>()"));
    }

    #[test]
    fn test_codegen_linq_with_orderby_desc() {
        let gen = RustGenerator::new();
        let expr = Expression::Linq(LinqQuery {
            from_var: "n".to_string(),
            in_collection: Box::new(Expression::Identifier("nums".to_string())),
            where_clause: None,
            orderby_clause: Some(Box::new(Expression::Identifier("n".to_string()))),
            descending: true,
            select_clause: Box::new(Expression::Identifier("n".to_string())),
        });
        let code = gen.gen_expression(&expr);
        assert!(code.contains("sort_by_key(|n| n)"));
        assert!(code.contains("if true { _ltmp.reverse(); }"));
    }

    #[test]
    fn test_codegen_query_expression() {
        let gen = RustGenerator::new();
        let expr = Expression::Query(SurrealQueryNode {
            raw_query: "SELECT * FROM users WHERE age > 18".to_string(),
        });
        let code = gen.gen_expression(&expr);
        assert!(code.contains("__varg_query("));
        assert!(code.contains("SELECT * FROM users WHERE age > 18"));
    }

    #[test]
    fn test_codegen_prompt_literal_interpolation() {
        let gen = RustGenerator::new();
        let expr = Expression::PromptLiteral("Hello ${name}, you have ${count} items".to_string());
        let code = gen.gen_expression(&expr);
        assert!(code.contains("Prompt { text: format!"));
        assert!(code.contains("name"));
        assert!(code.contains("count"));
    }

    #[test]
    fn test_codegen_prompt_literal_plain() {
        let gen = RustGenerator::new();
        let expr = Expression::PromptLiteral("Hello world".to_string());
        let code = gen.gen_expression(&expr);
        assert!(code.contains("Prompt { text: format!"));
        assert!(code.contains("Hello world"));
    }

    #[test]
    fn test_codegen_stream_statement() {
        let program = Program {
            no_std: true,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false, is_public: false,
                target_annotation: None, annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(), is_public: true, is_async: false,
                    annotations: vec![], type_params: vec![], constraints: vec![],
                    args: vec![], return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![
                        Statement::Stream(Expression::MethodCall {
                            caller: Box::new(Expression::Identifier("self".to_string())),
                            method_name: "llm_chat".to_string(),
                            args: vec![
                                Expression::Identifier("ctx".to_string()),
                                Expression::String("hi".to_string()),
                            ],
                        }),
                    ]}),
                }],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("__varg_llm_chat_stream("));
    }

    #[test]
    fn test_codegen_throw_statement() {
        let program = Program {
            no_std: true,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false, is_public: false,
                target_annotation: None, annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(), is_public: true, is_async: false,
                    annotations: vec![], type_params: vec![], constraints: vec![],
                    args: vec![], return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![
                        Statement::TryCatch {
                            try_block: Block { statements: vec![
                                Statement::Throw(Expression::String("something went wrong".to_string())),
                            ]},
                            catch_var: "err".to_string(),
                            catch_block: Block { statements: vec![
                                Statement::Print(Expression::Identifier("err".to_string())),
                            ]},
                        }
                    ]}),
                }],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("break 'varg_try Err("));
        assert!(code.contains("something went wrong"));
        assert!(code.contains("if let Err(mut err) = _varg_try_res"));
    }

    #[test]
    fn test_codegen_array_literal_direct() {
        let gen = RustGenerator::new();
        let expr = Expression::ArrayLiteral(vec![
            Expression::Int(1), Expression::Int(2), Expression::Int(3),
        ]);
        assert_eq!(gen.gen_expression(&expr), "vec![1, 2, 3]");
    }

    #[test]
    fn test_codegen_cosine_similarity_operator() {
        let gen = RustGenerator::new();
        let expr = Expression::BinaryOp {
            left: Box::new(Expression::Identifier("a".to_string())),
            operator: BinaryOperator::CosineSim,
            right: Box::new(Expression::Identifier("b".to_string())),
        };
        assert_eq!(gen.gen_expression(&expr), "__varg_cosine_sim(&a, &b)");
    }

    // ===== Plan 06: Destructuring CodeGen =====

    #[test]
    fn test_codegen_lambda_with_block_body() {
        let program = Program {
            no_std: true,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false, is_public: false,
                target_annotation: None, annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(), is_public: true, is_async: false,
                    annotations: vec![], type_params: vec![], constraints: vec![],
                    args: vec![], return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![
                        Statement::Let {
                            name: "process".to_string(),
                            ty: None,
                            value: Expression::Lambda {
                                params: vec![FieldDecl { name: "s".to_string(), ty: TypeNode::String }],
                                return_ty: None,
                                body: Box::new(LambdaBody::Block(Block {
                                    statements: vec![
                                        Statement::Return(Some(Expression::Identifier("s".to_string()))),
                                    ],
                                })),
                            },
                        },
                    ]}),
                }],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("|s: String|"));
        assert!(code.contains("return s;"));
    }

    // ===== New Operators: &&, ||, !, %, unary, string concat =====

    #[test]
    fn test_codegen_and_operator() {
        let gen = RustGenerator::new();
        let expr = Expression::BinaryOp {
            left: Box::new(Expression::Identifier("a".to_string())),
            operator: BinaryOperator::And,
            right: Box::new(Expression::Identifier("b".to_string())),
        };
        assert_eq!(gen.gen_expression(&expr), "a && b");
    }

    #[test]
    fn test_codegen_or_operator() {
        let gen = RustGenerator::new();
        let expr = Expression::BinaryOp {
            left: Box::new(Expression::Identifier("a".to_string())),
            operator: BinaryOperator::Or,
            right: Box::new(Expression::Identifier("b".to_string())),
        };
        assert_eq!(gen.gen_expression(&expr), "a || b");
    }

    #[test]
    fn test_codegen_modulo_operator() {
        let gen = RustGenerator::new();
        let expr = Expression::BinaryOp {
            left: Box::new(Expression::Int(10)),
            operator: BinaryOperator::Mod,
            right: Box::new(Expression::Int(3)),
        };
        assert_eq!(gen.gen_expression(&expr), "10 % 3");
    }

    #[test]
    fn test_codegen_unary_negate() {
        let gen = RustGenerator::new();
        let expr = Expression::UnaryOp {
            operator: UnaryOperator::Negate,
            operand: Box::new(Expression::Int(5)),
        };
        assert_eq!(gen.gen_expression(&expr), "-5");
    }

    #[test]
    fn test_codegen_unary_not() {
        let gen = RustGenerator::new();
        let expr = Expression::UnaryOp {
            operator: UnaryOperator::Not,
            operand: Box::new(Expression::Identifier("flag".to_string())),
        };
        assert_eq!(gen.gen_expression(&expr), "!flag");
    }

    #[test]
    fn test_codegen_string_concat() {
        let gen = RustGenerator::new();
        let expr = Expression::BinaryOp {
            left: Box::new(Expression::String("hello ".to_string())),
            operator: BinaryOperator::Add,
            right: Box::new(Expression::String("world".to_string())),
        };
        let code = gen.gen_expression(&expr);
        assert!(code.contains("format!"));
        assert!(code.contains("hello "));
        assert!(code.contains("world"));
    }

    #[test]
    fn test_codegen_string_concat_with_identifier() {
        let gen = RustGenerator::new();
        // "Hello " + name  — left is string, right is identifier
        let expr = Expression::BinaryOp {
            left: Box::new(Expression::String("Hello ".to_string())),
            operator: BinaryOperator::Add,
            right: Box::new(Expression::Identifier("name".to_string())),
        };
        let code = gen.gen_expression(&expr);
        assert!(code.contains("format!"));
    }

    #[test]
    fn test_codegen_unary_negate_nested() {
        let gen = RustGenerator::new();
        // -(a + b)
        let expr = Expression::UnaryOp {
            operator: UnaryOperator::Negate,
            operand: Box::new(Expression::BinaryOp {
                left: Box::new(Expression::Identifier("a".to_string())),
                operator: BinaryOperator::Add,
                right: Box::new(Expression::Identifier("b".to_string())),
            }),
        };
        let code = gen.gen_expression(&expr);
        assert!(code.starts_with('-'));
        assert!(code.contains("a + b"));
    }

    // ===== Wave 5: break / continue =====

    #[test]
    fn test_codegen_break() {
        let gen = RustGenerator::new();
        let block = Block { statements: vec![Statement::Break] };
        let code = gen.gen_block(&block, 1);
        assert!(code.contains("break;"));
    }

    #[test]
    fn test_codegen_continue() {
        let gen = RustGenerator::new();
        let block = Block { statements: vec![Statement::Continue] };
        let code = gen.gen_block(&block, 1);
        assert!(code.contains("continue;"));
    }

    // ===== Wave 5: String Methods =====

    #[test]
    fn test_codegen_string_len() {
        let gen = RustGenerator::new();
        let expr = Expression::MethodCall {
            caller: Box::new(Expression::Identifier("s".to_string())),
            method_name: "len".to_string(),
            args: vec![],
        };
        assert_eq!(gen.gen_expression(&expr), "s.len() as i64");
    }

    #[test]
    fn test_codegen_string_contains() {
        let gen = RustGenerator::new();
        let expr = Expression::MethodCall {
            caller: Box::new(Expression::Identifier("s".to_string())),
            method_name: "contains".to_string(),
            args: vec![Expression::String("hello".to_string())],
        };
        let code = gen.gen_expression(&expr);
        assert!(code.contains("s.contains("));
        assert!(code.contains("hello"));
    }

    #[test]
    fn test_codegen_string_to_upper() {
        let gen = RustGenerator::new();
        let expr = Expression::MethodCall {
            caller: Box::new(Expression::Identifier("name".to_string())),
            method_name: "to_upper".to_string(),
            args: vec![],
        };
        assert_eq!(gen.gen_expression(&expr), "name.to_uppercase()");
    }

    #[test]
    fn test_codegen_string_substring() {
        let gen = RustGenerator::new();
        let expr = Expression::MethodCall {
            caller: Box::new(Expression::Identifier("text".to_string())),
            method_name: "substring".to_string(),
            args: vec![Expression::Int(2), Expression::Int(5)],
        };
        let code = gen.gen_expression(&expr);
        assert!(code.contains("text.chars().skip(2 as usize).take(5 as usize)"));
    }

    // ===== Wave 5: Collection Methods =====

    #[test]
    fn test_codegen_array_len() {
        let gen = RustGenerator::new();
        let expr = Expression::MethodCall {
            caller: Box::new(Expression::Identifier("arr".to_string())),
            method_name: "len".to_string(),
            args: vec![],
        };
        assert_eq!(gen.gen_expression(&expr), "arr.len() as i64");
    }

    #[test]
    fn test_codegen_array_push() {
        let gen = RustGenerator::new();
        let expr = Expression::MethodCall {
            caller: Box::new(Expression::Identifier("arr".to_string())),
            method_name: "push".to_string(),
            args: vec![Expression::Int(42)],
        };
        assert_eq!(gen.gen_expression(&expr), "arr.push(42)");
    }

    #[test]
    fn test_codegen_map_keys() {
        let gen = RustGenerator::new();
        let expr = Expression::MethodCall {
            caller: Box::new(Expression::Identifier("map".to_string())),
            method_name: "keys".to_string(),
            args: vec![],
        };
        assert_eq!(gen.gen_expression(&expr), "map.keys().cloned().collect::<Vec<_>>()");
    }

    #[test]
    fn test_codegen_map_contains_key() {
        let gen = RustGenerator::new();
        let expr = Expression::MethodCall {
            caller: Box::new(Expression::Identifier("map".to_string())),
            method_name: "contains_key".to_string(),
            args: vec![Expression::String("key".to_string())],
        };
        let code = gen.gen_expression(&expr);
        assert!(code.contains("map.contains_key("));
    }

    // ===== Wave 5: async / await =====

    #[test]
    fn test_codegen_async_method() {
        let program = Program {
            no_std: true,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false, is_public: false,
                target_annotation: None, annotations: vec![],
                methods: vec![MethodDecl {
                    name: "FetchData".to_string(), is_public: true, is_async: true,
                    annotations: vec![], type_params: vec![], constraints: vec![],
                    args: vec![], return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![
                        Statement::Print(Expression::String("hello".to_string())),
                    ]}),
                }],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("async fn FetchData"));
    }

    #[test]
    fn test_codegen_await_expression() {
        let gen = RustGenerator::new();
        let expr = Expression::Await(Box::new(
            Expression::MethodCall {
                caller: Box::new(Expression::Identifier("client".to_string())),
                method_name: "fetch".to_string(),
                args: vec![Expression::String("url".to_string())],
            }
        ));
        let code = gen.gen_expression(&expr);
        assert!(code.contains(".await"));
    }

    // ===== Wave 5: const =====

    #[test]
    fn test_codegen_const_with_type() {
        let gen = RustGenerator::new();
        let block = Block { statements: vec![
            Statement::Const {
                name: "MAX".to_string(),
                ty: Some(TypeNode::Int),
                value: Expression::Int(100),
            },
        ]};
        let code = gen.gen_block(&block, 1);
        assert!(code.contains("let MAX: i64 = 100;"));
    }

    #[test]
    fn test_codegen_const_without_type() {
        let gen = RustGenerator::new();
        let block = Block { statements: vec![
            Statement::Const {
                name: "NAME".to_string(),
                ty: None,
                value: Expression::String("varg".to_string()),
            },
        ]};
        let code = gen.gen_block(&block, 1);
        assert!(code.contains("let NAME = \"varg\".to_string();"));
    }

    // ===== Wave 5b: Index/Property/Compound Assignment =====

    #[test]
    fn test_codegen_index_assign() {
        let gen = RustGenerator::new();
        let block = Block { statements: vec![
            Statement::IndexAssign {
                target: Expression::Identifier("arr".to_string()),
                index: Expression::Int(0),
                value: Expression::Int(42),
            },
        ]};
        let code = gen.gen_block(&block, 1);
        assert!(code.contains("arr[0 as usize] = 42;"));
    }

    #[test]
    fn test_codegen_property_assign() {
        let gen = RustGenerator::new();
        let block = Block { statements: vec![
            Statement::PropertyAssign {
                target: Expression::Identifier("obj".to_string()),
                property: "name".to_string(),
                value: Expression::String("alice".to_string()),
            },
        ]};
        let code = gen.gen_block(&block, 1);
        assert!(code.contains("obj.name = \"alice\".to_string();"));
    }

    #[test]
    fn test_codegen_map_insert_via_index_assign() {
        let gen = RustGenerator::new();
        let block = Block { statements: vec![
            Statement::IndexAssign {
                target: Expression::Identifier("map".to_string()),
                index: Expression::String("key".to_string()),
                value: Expression::String("value".to_string()),
            },
        ]};
        let code = gen.gen_block(&block, 1);
        assert!(code.contains("map.insert("));
    }
}
