use varg_ast::ast::*;

pub struct RustGenerator;

impl RustGenerator {
    pub fn new() -> Self {
        Self {}
    }

    pub fn generate(&self, program: &Program) -> String {
        let mut output = String::new();
        output.push_str("// --- AUTOGENERATED BY Varg Compiler ---\n");
        output.push_str("use varg_os_types::*;\n\n");
        
        // Inject Core In-built modules (Crypto MVP)
        output.push_str("// --- varg CRYPTO CORE ---\n");
        output.push_str("use aes_gcm::{aead::{Aead, KeyInit, OsRng}, Aes256Gcm, Nonce};\n");
        output.push_str("use pbkdf2::pbkdf2_hmac;\n");
        output.push_str("use sha2::Sha512;\n");
        output.push_str("use rand::RngCore;\n");
        output.push_str("use base64::{engine::general_purpose::STANDARD, Engine as _};\n\n");
        
        output.push_str("fn __varg_derive_key(key: &str, salt: &[u8]) -> [u8; 32] {\n");
        output.push_str("    let mut derived_key = [0u8; 32];\n");
        output.push_str("    pbkdf2_hmac::<Sha512>(key.as_bytes(), salt, 600_000, &mut derived_key);\n");
        output.push_str("    derived_key\n");
        output.push_str("}\n\n");

        output.push_str("fn __varg_encrypt(data: &str, key: &str) -> String {\n");
        output.push_str("    let mut salt = [0u8; 16];\n");
        output.push_str("    OsRng.fill_bytes(&mut salt);\n");
        output.push_str("    let derived_key = __varg_derive_key(key, &salt);\n");
        output.push_str("    let cipher = Aes256Gcm::new_from_slice(&derived_key).unwrap();\n");
        output.push_str("    let mut nonce_bytes = [0u8; 12];\n");
        output.push_str("    OsRng.fill_bytes(&mut nonce_bytes);\n");
        output.push_str("    let nonce = Nonce::from_slice(&nonce_bytes);\n");
        output.push_str("    let ciphertext = cipher.encrypt(nonce, data.as_bytes()).expect(\"[VargOS] Encryption failed\");\n");
        
        // Pack: Salt (16) + Nonce (12) + Ciphertext
        output.push_str("    let mut packed = Vec::with_capacity(16 + 12 + ciphertext.len());\n");
        output.push_str("    packed.extend_from_slice(&salt);\n");
        output.push_str("    packed.extend_from_slice(&nonce_bytes);\n");
        output.push_str("    packed.extend_from_slice(&ciphertext);\n");
        output.push_str("    STANDARD.encode(packed)\n");
        output.push_str("}\n\n");

        output.push_str("fn __varg_decrypt(data: &str, key: &str) -> String {\n");
        output.push_str("    let packed = STANDARD.decode(data).expect(\"[VargOS] Invalid Base64 Encryption Payload\");\n");
        output.push_str("    if packed.len() < 16 + 12 {\n");
        output.push_str("         panic!(\"[VargOS] Payload too short for AES-GCM.\");\n");
        output.push_str("    }\n");
        output.push_str("    let salt = &packed[0..16];\n");
        output.push_str("    let nonce_bytes = &packed[16..28];\n");
        output.push_str("    let ciphertext = &packed[28..];\n");
        output.push_str("    let derived_key = __varg_derive_key(key, salt);\n");
        output.push_str("    let cipher = Aes256Gcm::new_from_slice(&derived_key).unwrap();\n");
        output.push_str("    let nonce = Nonce::from_slice(nonce_bytes);\n");
        output.push_str("    let plaintext = cipher.decrypt(nonce, ciphertext).expect(\"[VargOS] Decryption failed or wrong password\");\n");
        output.push_str("    String::from_utf8(plaintext).unwrap()\n");
        output.push_str("}\n\n");

        // Inject Networking (Phase 11)
        output.push_str("// --- varg NETWORKING CORE ---\n");
        output.push_str("fn __varg_fetch(url: &str, method: &str, headers: std::collections::HashMap<String, String>, body: &str) -> String {\n");
        output.push_str("    let mut cmd = std::process::Command::new(\"curl\");\n");
        output.push_str("    cmd.arg(\"-s\").arg(\"-X\").arg(method);\n");
        output.push_str("    for (k, v) in headers {\n");
        output.push_str("        cmd.arg(\"-H\").arg(format!(\"{}: {}\", k, v));\n");
        output.push_str("    }\n");
        output.push_str("    if !body.is_empty() {\n");
        output.push_str("        cmd.arg(\"-d\").arg(body);\n");
        output.push_str("    }\n");
        output.push_str("    cmd.arg(url);\n");
        output.push_str("    match cmd.output() {\n");
        output.push_str("        Ok(output) if output.status.success() => String::from_utf8_lossy(&output.stdout).to_string(),\n");
        output.push_str("        Ok(output) => format!(\"{{ \\\"error\\\": \\\"Request Failed: {}\\\" }}\", String::from_utf8_lossy(&output.stderr)),\n");
        output.push_str("        Err(e) => format!(\"{{ \\\"error\\\": \\\"Network Exec Error: {}\\\" }}\", e),\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");

        output.push_str("// --- varg EMBEDDED KV DATABASE (Phase 15) ---\n");
        output.push_str("fn __varg_query(query: &str) -> String {\n");
        output.push_str("    let db_path = \".varg_memory.json\";\n");
        output.push_str("    let mut db: std::collections::HashMap<String, String> = std::fs::read_to_string(db_path).ok().and_then(|s| serde_json::from_str(&s).ok()).unwrap_or_default();\n");
        output.push_str("    let parts: Vec<&str> = query.split_whitespace().collect();\n");
        output.push_str("    if parts.is_empty() { return \"[]\".to_string(); }\n");
        output.push_str("    let cmd = parts[0].to_uppercase();\n");
        output.push_str("    if cmd == \"SET\" && parts.len() >= 3 {\n");
        output.push_str("        let key = parts[1];\n");
        output.push_str("        let val = parts[2..].join(\" \");\n");
        output.push_str("        db.insert(key.to_string(), val);\n");
        output.push_str("        let _ = std::fs::write(db_path, serde_json::to_string(&db).unwrap());\n");
        output.push_str("        return \"{\\\"status\\\": \\\"ok\\\"}\".to_string();\n");
        output.push_str("    } else if cmd == \"GET\" && parts.len() == 2 {\n");
        output.push_str("        let key = parts[1];\n");
        output.push_str("        if let Some(val) = db.get(key) {\n");
        output.push_str("            // Attempt to parse val as JSON. If not JSON, return as string.\n");
        output.push_str("            if serde_json::from_str::<serde_json::Value>(val).is_ok() {\n");
        output.push_str("                return val.to_string();\n");
        output.push_str("            } else {\n");
        output.push_str("                return format!(\"\\\"{}\\\"\", val.replace(\"\\\"\", \"\\\\\\\"\"));\n");
        output.push_str("            }\n");
        output.push_str("        } else {\n");
        output.push_str("            return \"null\".to_string();\n");
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("    serde_json::to_string(&db).unwrap_or_else(|_| \"{}\".to_string())\n");
        output.push_str("}\n\n");

        output.push_str("// --- varg AUTONOMOUS LLM ENGINE (Phase 16) ---\n");
        output.push_str("fn __varg_llm_infer(prompt: &str, model: &str) -> String {\n");
        output.push_str("    let mut headers = std::collections::HashMap::new();\n");
        output.push_str("    headers.insert(\"Content-Type\".to_string(), \"application/json\".to_string());\n");
        output.push_str("    let safe_prompt = prompt.replace(\"\\\"\", \"\\\\\\\"\\n\");\n"); // Extremely naive escape for JSON MVP
        output.push_str("    let body = format!(\"{{\\\"model\\\": \\\"{}\\\", \\\"messages\\\": [{{\\\"role\\\": \\\"user\\\", \\\"content\\\": \\\"{}\\\"}}], \\\"stream\\\": false}}\", model, safe_prompt);\n");
        output.push_str("    let res = __varg_fetch(\"http://127.0.0.1:11434/api/chat\", \"POST\", headers, &body);\n");
        output.push_str("    if let Ok(json) = serde_json::from_str::<serde_json::Value>(&res) {\n");
        output.push_str("        if let Some(content) = json.get(\"message\").and_then(|m| m.get(\"content\")).and_then(|c| c.as_str()) {\n");
        output.push_str("            return content.to_string();\n");
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("    res\n");
        output.push_str("}\n\n");

        output.push_str("fn __varg_fetch_stream(url: &str, method: &str, headers: std::collections::HashMap<String, String>, body: &str) {\n");
        output.push_str("    let mut cmd = std::process::Command::new(\"curl\");\n");
        output.push_str("    cmd.arg(\"-N\").arg(\"-s\").arg(\"-X\").arg(method);\n");
        output.push_str("    for (k, v) in headers {\n");
        output.push_str("        cmd.arg(\"-H\").arg(format!(\"{}: {}\", k, v));\n");
        output.push_str("    }\n");
        output.push_str("    if !body.is_empty() { cmd.arg(\"-d\").arg(body); }\n");
        output.push_str("    cmd.arg(url);\n");
        output.push_str("    if let Ok(mut child) = cmd.stdout(std::process::Stdio::piped()).spawn() {\n");
        output.push_str("        if let Some(stdout) = child.stdout.take() {\n");
        output.push_str("            use std::io::{BufRead, BufReader, Write};\n");
        output.push_str("            for line in BufReader::new(stdout).lines().filter_map(Result::ok) {\n");
        output.push_str("                if let Ok(json) = serde_json::from_str::<serde_json::Value>(&line) {\n");
        output.push_str("                    if let Some(content) = json.get(\"message\").and_then(|m| m.get(\"content\")).and_then(|c| c.as_str()) {\n");
        output.push_str("                        print!(\"{}\", content); std::io::stdout().flush().unwrap();\n");
        output.push_str("                    }\n");
        output.push_str("                }\n");
        output.push_str("            }\n");
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("    println!();\n");
        output.push_str("}\n\n");

        output.push_str("fn __varg_llm_chat_stream(ctx: &mut Context, prompt: &str, model: &str) {\n");
        output.push_str("    let mut headers = std::collections::HashMap::new();\n");
        output.push_str("    headers.insert(\"Content-Type\".to_string(), \"application/json\".to_string());\n");
        output.push_str("    ctx.push(\"user\", prompt);\n");
        output.push_str("    let messages_json = serde_json::to_string(&ctx.messages).unwrap_or_else(|_| \"[]\".to_string());\n");
        output.push_str("    let body = format!(\"{{\\\"model\\\": \\\"{}\\\", \\\"messages\\\": {}, \\\"stream\\\": true}}\", model, messages_json);\n");
        output.push_str("    __varg_fetch_stream(\"http://127.0.0.1:11434/api/chat\", \"POST\", headers, &body);\n");
        output.push_str("    ctx.push(\"assistant\", \"[STREAMED_REPLY]\");\n"); 
        output.push_str("}\n\n");

        output.push_str("fn __varg_llm_infer_stream(prompt: &str, model: &str) {\n");
        output.push_str("    let mut headers = std::collections::HashMap::new();\n");
        output.push_str("    headers.insert(\"Content-Type\".to_string(), \"application/json\".to_string());\n");
        output.push_str("    let safe_prompt = prompt.replace(\"\\\"\", \"\\\\\\\"\\n\");\n");
        output.push_str("    let body = format!(\"{{\\\"model\\\": \\\"{}\\\", \\\"messages\\\": [{{\\\"role\\\": \\\"user\\\", \\\"content\\\": \\\"{}\\\"}}], \\\"stream\\\": true}}\", model, safe_prompt);\n");
        output.push_str("    __varg_fetch_stream(\"http://127.0.0.1:11434/api/chat\", \"POST\", headers, &body);\n");
        output.push_str("}\n\n");

        output.push_str("fn __varg_create_context(id: &str) -> Context {\n    Context::new(id)\n}\n\n");
        
        output.push_str("fn __varg_context_from(data: &str) -> Context {\n");
        output.push_str("    let mut ctx = Context::new(\"rag_context\");\n");
        output.push_str("    ctx.push(\"system\", &format!(\"Use the following context to answer:\\n{}\", data));\n");
        output.push_str("    ctx\n");
        output.push_str("}\n\n");

        output.push_str("fn __varg_llm_chat(ctx: &mut Context, prompt: &str, model: &str) -> String {\n");
        output.push_str("    let mut headers = std::collections::HashMap::new();\n");
        output.push_str("    headers.insert(\"Content-Type\".to_string(), \"application/json\".to_string());\n");
        output.push_str("    ctx.push(\"user\", prompt);\n");
        output.push_str("    let messages_json = serde_json::to_string(&ctx.messages).unwrap_or_else(|_| \"[]\".to_string());\n");
        output.push_str("    let body = format!(\"{{\\\"model\\\": \\\"{}\\\", \\\"messages\\\": {}, \\\"stream\\\": false}}\", model, messages_json);\n");
        output.push_str("    let res = __varg_fetch(\"http://127.0.0.1:11434/api/chat\", \"POST\", headers, &body);\n");
        output.push_str("    if let Ok(json) = serde_json::from_str::<serde_json::Value>(&res) {\n");
        output.push_str("        if let Some(content) = json.get(\"message\").and_then(|m| m.get(\"content\")).and_then(|c| c.as_str()) {\n");
        output.push_str("            ctx.push(\"assistant\", content);\n");
        output.push_str("            return content.to_string();\n");
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("    res\n");
        output.push_str("}\n\n");

        output.push_str("// --- varg VECTOR MATH (Phase 20.B) ---\n");
        output.push_str("fn __varg_cosine_sim(a: &Tensor, b: &Tensor) -> f32 {\n");
        output.push_str("    let dot: f32 = a.data.iter().zip(b.data.iter()).map(|(x, y)| x * y).sum();\n");
        output.push_str("    let mag_a: f32 = a.data.iter().map(|v| v * v).sum::<f32>().sqrt();\n");
        output.push_str("    let mag_b: f32 = b.data.iter().map(|v| v * v).sum::<f32>().sqrt();\n");
        output.push_str("    if mag_a == 0.0 || mag_b == 0.0 { 0.0 } else { dot / (mag_a * mag_b) }\n");
        output.push_str("}\n\n");
        output.push_str("fn __varg_create_tensor(data: Vec<i64>) -> Tensor {\n");
        output.push_str("    let data_f32 = data.into_iter().map(|x| x as f32).collect::<Vec<f32>>();\n");
        output.push_str("    let len = data_f32.len();\n");
        output.push_str("    Tensor { data: data_f32, shape: vec![len] }\n");
        output.push_str("}\n\n");

        for item in &program.items {
            output.push_str(&self.gen_item(item));
            output.push('\n');
        }

        output
    }

    fn gen_item(&self, item: &Item) -> String {
        match item {
            Item::Import(_) => String::new(), // Merged by vargc beforehand
            Item::TypeAlias { name, target } => {
                format!("type {} = {};\n", name, self.gen_type(target))
            },
            Item::Enum(e) => {
                let vis = if e.is_public { "pub " } else { "" };
                let mut out = format!("#[derive(Debug, Clone, PartialEq)]\n{}enum {} {{\n", vis, e.name);
                for variant in &e.variants {
                    if variant.fields.is_empty() {
                        out.push_str(&format!("    {},\n", variant.name));
                    } else {
                        let fields: Vec<String> = variant.fields.iter()
                            .map(|(name, ty)| format!("{}: {}", name, self.gen_type(ty)))
                            .collect();
                        out.push_str(&format!("    {} {{ {} }},\n", variant.name, fields.join(", ")));
                    }
                }
                out.push_str("}\n");
                out
            },
            Item::Struct(s) => {
                let vis = if s.is_public { "pub " } else { "" };
                let type_params = if s.type_params.is_empty() { "".to_string() } else { format!("<{}>", s.type_params.join(", ")) };
                let mut out = format!("{}struct {}{} {{\n", vis, s.name, type_params);
                for field in &s.fields {
                    // MVP: all generated fields are pub to the struct
                    out.push_str(&format!("    pub {}: {},\n", field.name, self.gen_type(&field.ty)));
                }
                out.push_str("}\n");
                out
            },
            Item::Contract(c) => {
                let vis = if c.is_public { "pub " } else { "" };
                let mut out = format!("{}trait {} {{\n", vis, c.name);
                for method in &c.methods {
                    out.push_str(&format!("    {};\n", self.gen_method_signature(method, true)));
                }
                out.push_str("}\n");
                out
            },
            Item::Agent(a) => {
                // An Agent translates to a struct with state, and an impl block
                let vis = if a.is_public { "pub " } else { "" };
                let mut out = format!("{}struct {} {{ /* Agent state */ }}\n\n", vis, a.name);
                out.push_str(&format!("impl {} {{\n", a.name));
                
                // Agent-level Annotations
                for ann in &a.annotations {
                    if ann.name == "CliCommand" {
                        out.push_str(&format!("    pub fn run_cli(&mut self) {{\n        println!(\"Starting CLI for agent {}...\");\n        // TODO: Map clap args to methods\n    }}\n", a.name));
                    }
                }

                for method in &a.methods {
                    // Method-level Annotations
                    for ann in &method.annotations {
                        if ann.name == "McpTool" {
                            let desc = ann.values.join(" ");
                            out.push_str(&format!("    pub fn {}_mcp_schema() -> String {{\n        r#\"{{ \"name\": \"{}\", \"description\": \"{}\" }}\"#.to_string()\n    }}\n", 
                                method.name, method.name, desc));
                        }
                    }

                    out.push_str(&format!("    {} {{\n", self.gen_method_signature(method, false)));
                    if let Some(body) = &method.body {
                        out.push_str(&self.gen_block(body, 2));
                    }
                    out.push_str("    }\n");
                }
                out.push_str("}\n");
                out
            }
        }
    }

    fn gen_method_signature(&self, method: &MethodDecl, force_no_vis: bool) -> String {
        let vis = if method.is_public && !force_no_vis { "pub " } else { "" };
        let args: Vec<String> = method.args.iter()
            .map(|a| format!("{}: {}", a.name, self.gen_type(&a.ty)))
            .collect();
        let arg_str = if args.is_empty() { "&mut self".to_string() } else { format!("&mut self, {}", args.join(", ")) };
        
        let ret_str = match &method.return_ty {
            Some(TypeNode::Void) | None => "".to_string(),
            Some(ty) => format!(" -> {}", self.gen_type(ty)),
        };

        let type_params = if method.type_params.is_empty() { "".to_string() } else { format!("<{}>", method.type_params.join(", ")) };
        let where_clause = if method.constraints.is_empty() {
            "".to_string()
        } else {
            let constraints: Vec<String> = method.constraints.iter()
                .map(|c| format!("{}: {}", c.type_param, c.bound))
                .collect();
            format!(" where {}", constraints.join(", "))
        };
        format!("{}fn {}{}({}){}{}", vis, method.name, type_params, arg_str, ret_str, where_clause)
    }

    fn gen_type(&self, ty: &TypeNode) -> String {
        match ty {
            TypeNode::Int => "i64".to_string(),
            TypeNode::Ulong => "u64".to_string(),
            TypeNode::String => "String".to_string(),
            TypeNode::Bool => "bool".to_string(),
            TypeNode::Void => "()".to_string(),
            
            // Native AI Types map directly to Rust OS types
            TypeNode::Prompt => "Prompt".to_string(),
            TypeNode::Context => "Context".to_string(),
            TypeNode::Tensor => "Tensor".to_string(),
            TypeNode::Embedding => "Embedding".to_string(),
            
            TypeNode::Nullable(inner) => format!("Option<{}>", self.gen_type(inner)),
            TypeNode::Result(ok, err) => format!("std::result::Result<{}, {}>", self.gen_type(ok), self.gen_type(err)),
            TypeNode::Error => "String".to_string(),
            TypeNode::TypeMapShort => "std::collections::HashMap<String, String>".to_string(),
            TypeNode::Array(inner) => format!("Vec<{}>", self.gen_type(inner)),
            TypeNode::List(inner) => format!("Vec<{}>", self.gen_type(inner)),
            TypeNode::Map(k, v) => format!("std::collections::HashMap<{}, {}>", self.gen_type(k), self.gen_type(v)),
            TypeNode::TypeVar(name) => name.clone(),
            TypeNode::Generic(name, args) => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.gen_type(a)).collect();
                format!("{}<{}>", name, arg_strs.join(", "))
            },
            TypeNode::Custom(name) => {
                if name == "Dynamic" {
                    "String".to_string() // MVP Fallback for empty []
                } else if name == "Iterator" {
                    "Vec<String>".to_string() // MVP for LINQ eval
                } else {
                    name.clone()
                }
            },
        }
    }

    fn gen_block(&self, block: &Block, indent_level: usize) -> String {
        let indent = "    ".repeat(indent_level);
        let mut out = String::new();
        for stmt in &block.statements {
            match stmt {
                Statement::Let { name, ty: _, value } => {
                    out.push_str(&format!("{}let mut {} = {};\n", indent, name, self.gen_expression(value)));
                },
                Statement::Assign { name, value } => {
                    out.push_str(&format!("{}{} = {};\n", indent, name, self.gen_expression(value)));
                },
                Statement::Return(Some(expr)) => {
                    out.push_str(&format!("{}return {};\n", indent, self.gen_expression(expr)));
                },
                Statement::Return(None) => {
                    out.push_str(&format!("{}return;\n", indent));
                },
                Statement::UnsafeBlock(inner) => {
                    // Hardware access / DB Queries map perfectly to Rust's unsafe block paradigm
                    out.push_str(&format!("{}unsafe {{\n", indent));
                    out.push_str(&self.gen_block(inner, indent_level + 1));
                    out.push_str(&format!("{}}}\n", indent));
                },

                Statement::If { condition, then_block, else_block } => {
                    out.push_str(&format!("{}if {} {{\n", indent, self.gen_expression(condition)));
                    out.push_str(&self.gen_block(then_block, indent_level + 1));
                    if let Some(eb) = else_block {
                        out.push_str(&format!("{}}} else {{\n", indent));
                        out.push_str(&self.gen_block(eb, indent_level + 1));
                    }
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::While { condition, body } => {
                    out.push_str(&format!("{}while {} {{\n", indent, self.gen_expression(condition)));
                    out.push_str(&self.gen_block(body, indent_level + 1));
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::For { init, condition, update, body } => {
                    out.push_str(&format!("{}{{\n", indent));
                    out.push_str(&self.gen_block(&Block { statements: vec![*init.clone()] }, indent_level + 1));
                    out.push_str(&format!("{}    while {} {{\n", indent, self.gen_expression(condition)));
                    out.push_str(&self.gen_block(body, indent_level + 2));
                    out.push_str(&self.gen_block(&Block { statements: vec![*update.clone()] }, indent_level + 2));
                    out.push_str(&format!("{}    }}\n", indent));
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::Foreach { item_name, collection, body } => {
                    out.push_str(&format!("{}for mut {} in {} {{\n", indent, item_name, self.gen_expression(collection)));
                    out.push_str(&self.gen_block(body, indent_level + 1));
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::Stream(expr) => {
                    if let Expression::MethodCall { method_name, args, .. } = expr {
                        if method_name == "llm_chat" {
                            let ctx = if args.len() > 0 { format!("&mut {}", self.gen_expression(&args[0])) } else { "\"\"".to_string() };
                            let prompt = if args.len() > 1 { self.gen_expression(&args[1]) } else { "\"\"".to_string() };
                            let model = if args.len() > 2 { self.gen_expression(&args[2]) } else { "\"llama3\"".to_string() };
                            out.push_str(&format!("{}__varg_llm_chat_stream({}, &{}, &{});\n", indent, ctx, prompt, model));
                        } else if method_name == "llm_infer" {
                            let prompt = if args.len() > 0 { self.gen_expression(&args[0]) } else { "\"\"".to_string() };
                            let model = if args.len() > 1 { self.gen_expression(&args[1]) } else { "\"llama3\"".to_string() };
                            out.push_str(&format!("{}__varg_llm_infer_stream(&{}, &{});\n", indent, prompt, model));
                        } else {
                            out.push_str(&format!("{}print!(\"{{}}\", {});\n{}use std::io::Write; std::io::stdout().flush().unwrap();\n", indent, self.gen_expression(expr), indent));
                        }
                    } else {
                        out.push_str(&format!("{}print!(\"{{}}\", {});\n{}use std::io::Write; std::io::stdout().flush().unwrap();\n", indent, self.gen_expression(expr), indent));
                    }
                },
                Statement::Print(expr) => {
                    out.push_str(&format!("{}println!(\"{{:?}}\", {});\n", indent, self.gen_expression(expr)));
                },
                Statement::Expr(expr) => {
                    out.push_str(&format!("{}{};\n", indent, self.gen_expression(expr)));
                },
                Statement::TryCatch { try_block, catch_var, catch_block } => {
                    out.push_str(&format!("{}#[allow(unreachable_code, unused_labels)]\n", indent));
                    out.push_str(&format!("{}let _varg_try_res: std::result::Result<(), String> = 'varg_try: {{\n", indent));
                    out.push_str(&self.gen_block(try_block, indent_level + 1));
                    out.push_str(&format!("{}    Ok(())\n", indent));
                    out.push_str(&format!("{}}};\n", indent));
                    out.push_str(&format!("{}if let Err(mut {}) = _varg_try_res {{\n", indent, catch_var));
                    out.push_str(&self.gen_block(catch_block, indent_level + 1));
                    out.push_str(&format!("{}}}\n", indent));
                },
                Statement::Throw(expr) => {
                    out.push_str(&format!("{}break 'varg_try Err(format!(\"{{}}\", {}));\n", indent, self.gen_expression(expr)));
                }
            }
        }
        out
    }

    fn gen_expression(&self, expr: &Expression) -> String {
        match expr {
            Expression::Null => "None".to_string(),
            Expression::Int(i) => i.to_string(),
            Expression::String(s) => format!("{:?}.to_string()", s),
            Expression::PromptLiteral(s) => {
                let mut stripped = String::new();
                let mut args = Vec::new();
                let mut chars = s.chars().peekable();
                while let Some(c) = chars.next() {
                    if c == '$' && chars.peek() == Some(&'{') {
                        chars.next(); // consume '{'
                        let mut expr_str = String::new();
                        while let Some(inner_c) = chars.next() {
                            if inner_c == '}' { break; }
                            expr_str.push(inner_c);
                        }
                        stripped.push_str("{}");
                        args.push(expr_str); 
                    } else if c == '{' {
                        stripped.push_str("{{");
                    } else if c == '}' {
                        stripped.push_str("}}");
                    } else {
                        stripped.push(c);
                    }
                }
                
                let args_joined = if args.is_empty() {
                    "".to_string()
                } else {
                    format!(", {}", args.join(", "))
                };
                
                format!("Prompt {{ text: format!({:?}{}) }}", stripped, args_joined)
            },
            Expression::Bool(b) => b.to_string(),
            Expression::Identifier(name) => name.clone(),
            Expression::BinaryOp { left, operator, right } => {
                if let BinaryOperator::CosineSim = operator {
                    return format!("__varg_cosine_sim(&{}, &{})", self.gen_expression(left), self.gen_expression(right));
                }

                let op = match operator {
                    BinaryOperator::Add => "+",
                    BinaryOperator::Sub => "-",
                    BinaryOperator::Mul => "*",
                    BinaryOperator::Div => "/",
                    BinaryOperator::Eq => "==",
                    BinaryOperator::NotEq => "!=",
                    BinaryOperator::Lt => "<",
                    BinaryOperator::Gt => ">",
                    BinaryOperator::LtEq => "<=",
                    BinaryOperator::GtEq => ">=",
                    BinaryOperator::CosineSim => unreachable!(),
                };
                format!("{} {} {}", self.gen_expression(left), op, self.gen_expression(right))
            },
            Expression::MethodCall { caller, method_name, args } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.gen_expression(a)).collect();
                if method_name == "encrypt" {
                    format!("__varg_encrypt(&{}, &{})", arg_strs[0], arg_strs[1])
                } else if method_name == "decrypt" {
                    format!("__varg_decrypt(&{}, &{})", arg_strs[0], arg_strs[1])
                } else if method_name == "fetch" {
                    let url = if arg_strs.len() > 0 { &arg_strs[0] } else { "\"\"" };
                    let met = if arg_strs.len() > 1 { &arg_strs[1] } else { "\"GET\"" };
                    let hdr = if arg_strs.len() > 2 { &arg_strs[2] } else { "std::collections::HashMap::new()" };
                    let bod = if arg_strs.len() > 3 { &arg_strs[3] } else { "\"\"" };
                    format!("__varg_fetch(&{}, &{}, {}, &{})", url, met, hdr, bod)
                } else if method_name == "llm_infer" {
                    let prompt = if arg_strs.len() > 0 { &arg_strs[0] } else { "\"\"" };
                    let model = if arg_strs.len() > 1 { &arg_strs[1] } else { "\"llama3\"" };
                    format!("__varg_llm_infer(&{}, &{})", prompt, model)
                } else if method_name == "llm_chat" {
                    let ctx = if arg_strs.len() > 0 { format!("&mut {}", arg_strs[0]) } else { "\"\"".to_string() };
                    let prompt = if arg_strs.len() > 1 { &arg_strs[1] } else { "\"\"" };
                    let model = if arg_strs.len() > 2 { &arg_strs[2] } else { "\"llama3\"" };
                    format!("__varg_llm_chat({}, &{}, &{})", ctx, prompt, model)
                } else if method_name == "to_json" {
                    format!("serde_json::to_string(&{}).unwrap_or_else(|e| format!(\"{{}}\", e))", arg_strs[0])
                } else if method_name == "from_json" {
                    // For MVP: parse into a flat String HashMap
                    format!("serde_json::from_str::<std::collections::HashMap<String, String>>(&{}).unwrap_or_default()", arg_strs[0])
                } else if method_name == "__varg_create_tensor" {
                    format!("__varg_create_tensor({})", arg_strs[0])
                } else if method_name == "__varg_create_context" {
                    format!("__varg_create_context(&{})", arg_strs[0])
                } else if method_name == "context_from" {
                    format!("__varg_context_from(&{})", arg_strs[0])
                } else if method_name == "file_read" {
                    format!("std::fs::read_to_string(&{}).unwrap_or_else(|e| format!(\"{{}}\", e))", arg_strs[0])
                } else if method_name == "file_write" {
                    format!("std::fs::write(&{}, &{}).unwrap()", arg_strs[0], arg_strs[1])
                } else if method_name == "time_now" {
                    "(std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_secs() as i64)".to_string()
                } else if method_name == "str_replace" {
                    format!("{}.replace(&{}, &{})", arg_strs[0], arg_strs[1], arg_strs[2])
                } else if method_name == "str_trim" {
                    format!("{}.trim().to_string()", arg_strs[0])
                } else if method_name == "str_split" {
                    format!("{}.split(&{}).map(|s| s.to_string()).collect::<Vec<String>>()", arg_strs[0], arg_strs[1])
                } else {
                    format!("{}.{}({})", self.gen_expression(caller), method_name, arg_strs.join(", "))
                }
            },
            Expression::PropertyAccess { caller, property_name } => {
                format!("{}.{}", self.gen_expression(caller), property_name)
            },
            Expression::IndexAccess { caller, index } => {
                let idx_str = self.gen_expression(index);
                if let Expression::Int(_) = **index {
                    format!("{}[{} as usize].clone()", self.gen_expression(caller), idx_str)
                } else {
                    format!("{}.get(&{}).unwrap().clone()", self.gen_expression(caller), idx_str)
                }
            },
            Expression::ArrayLiteral(elements) => {
                let elems: Vec<String> = elements.iter().map(|e| self.gen_expression(e)).collect();
                format!("vec![{}]", elems.join(", "))
            },
            Expression::MapLiteral(entries) => {
                let pairs: Vec<String> = entries.iter().map(|(k, v)| format!("({}, {})", self.gen_expression(k), self.gen_expression(v))).collect();
                format!("std::collections::HashMap::from([{}])", pairs.join(", "))
            },
            Expression::Linq(q) => {
                // LINQ transpiles into a highly efficient Rust Iterator chain
                let mut rust_query = format!("{}.clone().into_iter()", self.gen_expression(&q.in_collection));
                
                if let Some(where_c) = &q.where_clause {
                    rust_query.push_str(&format!(".filter(|{}| {})", q.from_var, self.gen_expression(where_c)));
                }

                if let Some(orderby_c) = &q.orderby_clause {
                    rust_query = format!("{{ let mut _ltmp = {}.collect::<Vec<_>>(); _ltmp.sort_by_key(|{}| {}); if {} {{ _ltmp.reverse(); }} _ltmp.into_iter() }}", 
                        rust_query, q.from_var, self.gen_expression(orderby_c), q.descending);
                }

                rust_query.push_str(&format!(".map(|{}| {}).collect::<Vec<_>>()", q.from_var, self.gen_expression(&q.select_clause)));
                
                rust_query
            },
            Expression::Query(q) => {
                // Native embedded DB call
                format!("__varg_query({:?})", q.raw_query)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_codegen_agent() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "MemoryAgent".to_string(),
                is_system: false,
                is_public: true,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Recall".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::String),
                    body: Some(Block {
                        statements: vec![
                            Statement::Let {
                                name: "mem".to_string(),
                                ty: Some(TypeNode::String),
                                value: Expression::String("Data".to_string()),
                            },
                            Statement::Return(Some(Expression::Identifier("mem".to_string()))),
                        ]
                    })
                }]
            })]
        };

        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        
        assert!(code.contains("pub struct MemoryAgent"));
        assert!(code.contains("pub fn Recall(&mut self) -> String"));
        assert!(code.contains("let mut mem = \"Data\".to_string();"));
        assert!(code.contains("return mem;"));
    }

    // ---- Plan 08: Extended CodeGen Coverage ----

    #[test]
    fn test_codegen_contract_trait() {
        let program = Program {
            no_std: false,
            items: vec![Item::Contract(ContractDef {
                name: "Searchable".to_string(),
                is_public: true,
                target_annotation: None,
                methods: vec![
                    MethodDecl {
                        name: "Find".to_string(),
                        is_public: true,
                        annotations: vec![],
                        type_params: vec![],
                        constraints: vec![],
                        args: vec![FieldDecl { name: "query".to_string(), ty: TypeNode::String }],
                        return_ty: Some(TypeNode::String),
                        body: None,
                    },
                ],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("pub trait Searchable"));
        assert!(code.contains("fn Find(&mut self, query: String) -> String;"));
    }

    #[test]
    fn test_codegen_struct() {
        let program = Program {
            no_std: false,
            items: vec![Item::Struct(StructDef {
                name: "UserProfile".to_string(),
                is_public: true,
                type_params: vec![],
                fields: vec![
                    FieldDecl { name: "name".to_string(), ty: TypeNode::String },
                    FieldDecl { name: "age".to_string(), ty: TypeNode::Int },
                    FieldDecl { name: "active".to_string(), ty: TypeNode::Bool },
                ],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("pub struct UserProfile"));
        assert!(code.contains("pub name: String,"));
        assert!(code.contains("pub age: i64,"));
        assert!(code.contains("pub active: bool,"));
    }

    #[test]
    fn test_codegen_if_else() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::If {
                                condition: Expression::Bool(true),
                                then_block: Block {
                                    statements: vec![Statement::Print(Expression::String("yes".to_string()))]
                                },
                                else_block: Some(Block {
                                    statements: vec![Statement::Print(Expression::String("no".to_string()))]
                                }),
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("if true {"));
        assert!(code.contains("} else {"));
    }

    #[test]
    fn test_codegen_while_loop() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::While {
                                condition: Expression::Bool(true),
                                body: Block {
                                    statements: vec![Statement::Return(None)]
                                },
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("while true {"));
        assert!(code.contains("return;"));
    }

    #[test]
    fn test_codegen_foreach() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Foreach {
                                item_name: "item".to_string(),
                                collection: Expression::Identifier("items".to_string()),
                                body: Block {
                                    statements: vec![Statement::Print(Expression::Identifier("item".to_string()))]
                                },
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("for mut item in items {"));
    }

    #[test]
    fn test_codegen_try_catch() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::TryCatch {
                                try_block: Block {
                                    statements: vec![Statement::Throw(Expression::String("error".to_string()))]
                                },
                                catch_var: "err".to_string(),
                                catch_block: Block {
                                    statements: vec![Statement::Print(Expression::Identifier("err".to_string()))]
                                },
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("'varg_try:"));
        assert!(code.contains("if let Err(mut err)"));
        assert!(code.contains("break 'varg_try Err("));
    }

    #[test]
    fn test_codegen_print() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Print(Expression::String("hello world".to_string()))
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("println!(\"{:?}\","));
    }

    #[test]
    fn test_codegen_binary_ops() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Let {
                                name: "sum".to_string(),
                                ty: None,
                                value: Expression::BinaryOp {
                                    left: Box::new(Expression::Int(1)),
                                    operator: BinaryOperator::Add,
                                    right: Box::new(Expression::Int(2)),
                                },
                            },
                            Statement::Let {
                                name: "eq".to_string(),
                                ty: None,
                                value: Expression::BinaryOp {
                                    left: Box::new(Expression::Int(1)),
                                    operator: BinaryOperator::Eq,
                                    right: Box::new(Expression::Int(1)),
                                },
                            },
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("1 + 2"));
        assert!(code.contains("1 == 1"));
    }

    #[test]
    fn test_codegen_array_literal() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::Let {
                                name: "arr".to_string(),
                                ty: None,
                                value: Expression::ArrayLiteral(vec![
                                    Expression::Int(1),
                                    Expression::Int(2),
                                    Expression::Int(3),
                                ]),
                            }
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("vec![1, 2, 3]"));
    }

    #[test]
    fn test_codegen_unsafe_block() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: true,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block {
                        statements: vec![
                            Statement::UnsafeBlock(Block {
                                statements: vec![Statement::Return(None)]
                            })
                        ]
                    })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("unsafe {"));
        assert!(code.contains("return;"));
    }

    #[test]
    fn test_codegen_method_with_where_clause() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Sort".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec!["T".to_string()],
                    constraints: vec![GenericConstraint {
                        type_param: "T".to_string(),
                        bound: "Comparable".to_string(),
                    }],
                    args: vec![],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![] })
                }]
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("fn Sort<T>"));
        assert!(code.contains("where T: Comparable"));
    }

    #[test]
    fn test_codegen_all_type_mappings() {
        // Test that all Varg types map to correct Rust types
        let gen = RustGenerator::new();
        assert_eq!(gen.gen_type(&TypeNode::Int), "i64");
        assert_eq!(gen.gen_type(&TypeNode::Ulong), "u64");
        assert_eq!(gen.gen_type(&TypeNode::String), "String");
        assert_eq!(gen.gen_type(&TypeNode::Bool), "bool");
        assert_eq!(gen.gen_type(&TypeNode::Void), "()");
        assert_eq!(gen.gen_type(&TypeNode::Prompt), "Prompt");
        assert_eq!(gen.gen_type(&TypeNode::Context), "Context");
        assert_eq!(gen.gen_type(&TypeNode::Tensor), "Tensor");
        assert_eq!(gen.gen_type(&TypeNode::Embedding), "Embedding");
        assert_eq!(gen.gen_type(&TypeNode::Error), "String");
        assert_eq!(gen.gen_type(&TypeNode::Array(Box::new(TypeNode::Int))), "Vec<i64>");
        assert_eq!(gen.gen_type(&TypeNode::List(Box::new(TypeNode::String))), "Vec<String>");
        assert_eq!(gen.gen_type(&TypeNode::Nullable(Box::new(TypeNode::Bool))), "Option<bool>");
        assert_eq!(gen.gen_type(&TypeNode::Map(Box::new(TypeNode::String), Box::new(TypeNode::Int))), "std::collections::HashMap<String, i64>");
        assert_eq!(gen.gen_type(&TypeNode::Result(Box::new(TypeNode::String), Box::new(TypeNode::Error))), "std::result::Result<String, String>");
        assert_eq!(gen.gen_type(&TypeNode::TypeVar("T".to_string())), "T");
    }

    #[test]
    fn test_codegen_struct_with_generics() {
        let program = Program {
            no_std: false,
            items: vec![Item::Struct(StructDef {
                name: "Container".to_string(),
                is_public: true,
                type_params: vec!["T".to_string()],
                fields: vec![
                    FieldDecl { name: "value".to_string(), ty: TypeNode::TypeVar("T".to_string()) },
                ],
            })]
        };
        let gen = RustGenerator::new();
        let code = gen.generate(&program);
        assert!(code.contains("pub struct Container<T>"));
        assert!(code.contains("pub value: T,"));
    }

    // ---- Plan 07 Tests ----

    #[test]
    fn test_codegen_enum() {
        let program = Program {
            no_std: false,
            items: vec![Item::Enum(EnumDef {
                name: "Status".to_string(),
                is_public: true,
                variants: vec![
                    EnumVariant { name: "Active".to_string(), fields: vec![] },
                    EnumVariant { name: "Suspended".to_string(), fields: vec![
                        ("reason".to_string(), TypeNode::String),
                    ]},
                ],
            })]
        };

        let gen = RustGenerator::new();
        let code = gen.generate(&program);

        assert!(code.contains("pub enum Status"));
        assert!(code.contains("Active,"));
        assert!(code.contains("Suspended { reason: String }"));
    }

    #[test]
    fn test_codegen_type_alias() {
        let program = Program {
            no_std: false,
            items: vec![Item::TypeAlias {
                name: "UserId".to_string(),
                target: TypeNode::String,
            }]
        };

        let gen = RustGenerator::new();
        let code = gen.generate(&program);

        assert!(code.contains("type UserId = String;"));
    }

    #[test]
    fn test_codegen_nullable_type() {
        let program = Program {
            no_std: false,
            items: vec![Item::Agent(AgentDef {
                name: "Test".to_string(),
                is_system: false,
                is_public: false,
                target_annotation: None,
                annotations: vec![],
                methods: vec![MethodDecl {
                    name: "Run".to_string(),
                    is_public: true,
                    annotations: vec![],
                    type_params: vec![],
                    constraints: vec![],
                    args: vec![FieldDecl {
                        name: "name".to_string(),
                        ty: TypeNode::Nullable(Box::new(TypeNode::String)),
                    }],
                    return_ty: Some(TypeNode::Void),
                    body: Some(Block { statements: vec![
                        Statement::Let {
                            name: "x".to_string(),
                            ty: None,
                            value: Expression::Null,
                        }
                    ]})
                }]
            })]
        };

        let gen = RustGenerator::new();
        let code = gen.generate(&program);

        assert!(code.contains("name: Option<String>"));
        assert!(code.contains("let mut x = None;"));
    }
}
